/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWalletRouteImport } from './routes/_layout/wallet'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutOffersRouteImport } from './routes/_layout/offers'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHelpRouteImport } from './routes/_layout/help'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutUUserIdRouteImport } from './routes/_layout/u.$userId'
import { Route as LayoutOrdersOrderIdRouteImport } from './routes/_layout/orders.$orderId'
import { Route as LayoutLegalTermsRouteImport } from './routes/_layout/legal.terms'
import { Route as LayoutLegalRegulationRouteImport } from './routes/_layout/legal.regulation'
import { Route as LayoutLegalPrivacyRouteImport } from './routes/_layout/legal.privacy'
import { Route as LayoutLegalAboutRouteImport } from './routes/_layout/legal.about'
import { Route as LayoutItemsCreateRouteImport } from './routes/_layout/items.create'
import { Route as LayoutItemsListingIdRouteImport } from './routes/_layout/items.$listingId'
import { Route as LayoutHelpSafetyRouteImport } from './routes/_layout/help.safety'
import { Route as LayoutHelpFaqRouteImport } from './routes/_layout/help.faq'
import { Route as LayoutHelpContactRouteImport } from './routes/_layout/help.contact'
import { Route as LayoutEscrowOrderIdRouteImport } from './routes/_layout/escrow.$orderId'
import { Route as LayoutCategoriesSlugRouteImport } from './routes/_layout/categories.$slug'
import { Route as LayoutAdminModerationRouteImport } from './routes/_layout/admin.moderation'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWalletRoute = LayoutWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOffersRoute = LayoutOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHelpRoute = LayoutHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUUserIdRoute = LayoutUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersOrderIdRoute = LayoutOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => LayoutOrdersRoute,
} as any)
const LayoutLegalTermsRoute = LayoutLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalRegulationRoute = LayoutLegalRegulationRouteImport.update({
  id: '/legal/regulation',
  path: '/legal/regulation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalPrivacyRoute = LayoutLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalAboutRoute = LayoutLegalAboutRouteImport.update({
  id: '/legal/about',
  path: '/legal/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsCreateRoute = LayoutItemsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutItemsRoute,
} as any)
const LayoutItemsListingIdRoute = LayoutItemsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => LayoutItemsRoute,
} as any)
const LayoutHelpSafetyRoute = LayoutHelpSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => LayoutHelpRoute,
} as any)
const LayoutHelpFaqRoute = LayoutHelpFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutHelpRoute,
} as any)
const LayoutHelpContactRoute = LayoutHelpContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutHelpRoute,
} as any)
const LayoutEscrowOrderIdRoute = LayoutEscrowOrderIdRouteImport.update({
  id: '/escrow/$orderId',
  path: '/escrow/$orderId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesSlugRoute = LayoutCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutCategoriesRoute,
} as any)
const LayoutAdminModerationRoute = LayoutAdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/categories': typeof LayoutCategoriesRouteWithChildren
  '/help': typeof LayoutHelpRouteWithChildren
  '/items': typeof LayoutItemsRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRouteWithChildren
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/wallet': typeof LayoutWalletRoute
  '/search/': typeof SearchIndexRoute
  '/admin/moderation': typeof LayoutAdminModerationRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/escrow/$orderId': typeof LayoutEscrowOrderIdRoute
  '/help/contact': typeof LayoutHelpContactRoute
  '/help/faq': typeof LayoutHelpFaqRoute
  '/help/safety': typeof LayoutHelpSafetyRoute
  '/items/$listingId': typeof LayoutItemsListingIdRoute
  '/items/create': typeof LayoutItemsCreateRoute
  '/legal/about': typeof LayoutLegalAboutRoute
  '/legal/privacy': typeof LayoutLegalPrivacyRoute
  '/legal/regulation': typeof LayoutLegalRegulationRoute
  '/legal/terms': typeof LayoutLegalTermsRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/u/$userId': typeof LayoutUUserIdRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/categories': typeof LayoutCategoriesRouteWithChildren
  '/help': typeof LayoutHelpRouteWithChildren
  '/items': typeof LayoutItemsRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRouteWithChildren
  '/search': typeof SearchIndexRoute
  '/settings': typeof LayoutSettingsRoute
  '/wallet': typeof LayoutWalletRoute
  '/': typeof LayoutIndexRoute
  '/admin/moderation': typeof LayoutAdminModerationRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/escrow/$orderId': typeof LayoutEscrowOrderIdRoute
  '/help/contact': typeof LayoutHelpContactRoute
  '/help/faq': typeof LayoutHelpFaqRoute
  '/help/safety': typeof LayoutHelpSafetyRoute
  '/items/$listingId': typeof LayoutItemsListingIdRoute
  '/items/create': typeof LayoutItemsCreateRoute
  '/legal/about': typeof LayoutLegalAboutRoute
  '/legal/privacy': typeof LayoutLegalPrivacyRoute
  '/legal/regulation': typeof LayoutLegalRegulationRoute
  '/legal/terms': typeof LayoutLegalTermsRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/u/$userId': typeof LayoutUUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/categories': typeof LayoutCategoriesRouteWithChildren
  '/_layout/help': typeof LayoutHelpRouteWithChildren
  '/_layout/items': typeof LayoutItemsRouteWithChildren
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/offers': typeof LayoutOffersRoute
  '/_layout/orders': typeof LayoutOrdersRouteWithChildren
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/wallet': typeof LayoutWalletRoute
  '/_layout/': typeof LayoutIndexRoute
  '/search/': typeof SearchIndexRoute
  '/_layout/admin/moderation': typeof LayoutAdminModerationRoute
  '/_layout/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/_layout/escrow/$orderId': typeof LayoutEscrowOrderIdRoute
  '/_layout/help/contact': typeof LayoutHelpContactRoute
  '/_layout/help/faq': typeof LayoutHelpFaqRoute
  '/_layout/help/safety': typeof LayoutHelpSafetyRoute
  '/_layout/items/$listingId': typeof LayoutItemsListingIdRoute
  '/_layout/items/create': typeof LayoutItemsCreateRoute
  '/_layout/legal/about': typeof LayoutLegalAboutRoute
  '/_layout/legal/privacy': typeof LayoutLegalPrivacyRoute
  '/_layout/legal/regulation': typeof LayoutLegalRegulationRoute
  '/_layout/legal/terms': typeof LayoutLegalTermsRoute
  '/_layout/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/_layout/u/$userId': typeof LayoutUUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/categories'
    | '/help'
    | '/items'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/search/'
    | '/admin/moderation'
    | '/categories/$slug'
    | '/escrow/$orderId'
    | '/help/contact'
    | '/help/faq'
    | '/help/safety'
    | '/items/$listingId'
    | '/items/create'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/regulation'
    | '/legal/terms'
    | '/orders/$orderId'
    | '/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/categories'
    | '/help'
    | '/items'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/'
    | '/admin/moderation'
    | '/categories/$slug'
    | '/escrow/$orderId'
    | '/help/contact'
    | '/help/faq'
    | '/help/safety'
    | '/items/$listingId'
    | '/items/create'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/regulation'
    | '/legal/terms'
    | '/orders/$orderId'
    | '/u/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/categories'
    | '/_layout/help'
    | '/_layout/items'
    | '/_layout/notifications'
    | '/_layout/offers'
    | '/_layout/orders'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/wallet'
    | '/_layout/'
    | '/search/'
    | '/_layout/admin/moderation'
    | '/_layout/categories/$slug'
    | '/_layout/escrow/$orderId'
    | '/_layout/help/contact'
    | '/_layout/help/faq'
    | '/_layout/help/safety'
    | '/_layout/items/$listingId'
    | '/_layout/items/create'
    | '/_layout/legal/about'
    | '/_layout/legal/privacy'
    | '/_layout/legal/regulation'
    | '/_layout/legal/terms'
    | '/_layout/orders/$orderId'
    | '/_layout/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wallet': {
      id: '/_layout/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof LayoutWalletRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offers': {
      id: '/_layout/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof LayoutOffersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/help': {
      id: '/_layout/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof LayoutHelpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/u/$userId': {
      id: '/_layout/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof LayoutUUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/$orderId': {
      id: '/_layout/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof LayoutOrdersOrderIdRouteImport
      parentRoute: typeof LayoutOrdersRoute
    }
    '/_layout/legal/terms': {
      id: '/_layout/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LayoutLegalTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/regulation': {
      id: '/_layout/legal/regulation'
      path: '/legal/regulation'
      fullPath: '/legal/regulation'
      preLoaderRoute: typeof LayoutLegalRegulationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/privacy': {
      id: '/_layout/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LayoutLegalPrivacyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/about': {
      id: '/_layout/legal/about'
      path: '/legal/about'
      fullPath: '/legal/about'
      preLoaderRoute: typeof LayoutLegalAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items/create': {
      id: '/_layout/items/create'
      path: '/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof LayoutItemsCreateRouteImport
      parentRoute: typeof LayoutItemsRoute
    }
    '/_layout/items/$listingId': {
      id: '/_layout/items/$listingId'
      path: '/$listingId'
      fullPath: '/items/$listingId'
      preLoaderRoute: typeof LayoutItemsListingIdRouteImport
      parentRoute: typeof LayoutItemsRoute
    }
    '/_layout/help/safety': {
      id: '/_layout/help/safety'
      path: '/safety'
      fullPath: '/help/safety'
      preLoaderRoute: typeof LayoutHelpSafetyRouteImport
      parentRoute: typeof LayoutHelpRoute
    }
    '/_layout/help/faq': {
      id: '/_layout/help/faq'
      path: '/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof LayoutHelpFaqRouteImport
      parentRoute: typeof LayoutHelpRoute
    }
    '/_layout/help/contact': {
      id: '/_layout/help/contact'
      path: '/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof LayoutHelpContactRouteImport
      parentRoute: typeof LayoutHelpRoute
    }
    '/_layout/escrow/$orderId': {
      id: '/_layout/escrow/$orderId'
      path: '/escrow/$orderId'
      fullPath: '/escrow/$orderId'
      preLoaderRoute: typeof LayoutEscrowOrderIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories/$slug': {
      id: '/_layout/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof LayoutCategoriesSlugRouteImport
      parentRoute: typeof LayoutCategoriesRoute
    }
    '/_layout/admin/moderation': {
      id: '/_layout/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof LayoutAdminModerationRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminModerationRoute: typeof LayoutAdminModerationRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminModerationRoute: LayoutAdminModerationRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutCategoriesRouteChildren {
  LayoutCategoriesSlugRoute: typeof LayoutCategoriesSlugRoute
}

const LayoutCategoriesRouteChildren: LayoutCategoriesRouteChildren = {
  LayoutCategoriesSlugRoute: LayoutCategoriesSlugRoute,
}

const LayoutCategoriesRouteWithChildren =
  LayoutCategoriesRoute._addFileChildren(LayoutCategoriesRouteChildren)

interface LayoutHelpRouteChildren {
  LayoutHelpContactRoute: typeof LayoutHelpContactRoute
  LayoutHelpFaqRoute: typeof LayoutHelpFaqRoute
  LayoutHelpSafetyRoute: typeof LayoutHelpSafetyRoute
}

const LayoutHelpRouteChildren: LayoutHelpRouteChildren = {
  LayoutHelpContactRoute: LayoutHelpContactRoute,
  LayoutHelpFaqRoute: LayoutHelpFaqRoute,
  LayoutHelpSafetyRoute: LayoutHelpSafetyRoute,
}

const LayoutHelpRouteWithChildren = LayoutHelpRoute._addFileChildren(
  LayoutHelpRouteChildren,
)

interface LayoutItemsRouteChildren {
  LayoutItemsListingIdRoute: typeof LayoutItemsListingIdRoute
  LayoutItemsCreateRoute: typeof LayoutItemsCreateRoute
}

const LayoutItemsRouteChildren: LayoutItemsRouteChildren = {
  LayoutItemsListingIdRoute: LayoutItemsListingIdRoute,
  LayoutItemsCreateRoute: LayoutItemsCreateRoute,
}

const LayoutItemsRouteWithChildren = LayoutItemsRoute._addFileChildren(
  LayoutItemsRouteChildren,
)

interface LayoutOrdersRouteChildren {
  LayoutOrdersOrderIdRoute: typeof LayoutOrdersOrderIdRoute
}

const LayoutOrdersRouteChildren: LayoutOrdersRouteChildren = {
  LayoutOrdersOrderIdRoute: LayoutOrdersOrderIdRoute,
}

const LayoutOrdersRouteWithChildren = LayoutOrdersRoute._addFileChildren(
  LayoutOrdersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutCategoriesRoute: typeof LayoutCategoriesRouteWithChildren
  LayoutHelpRoute: typeof LayoutHelpRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRouteWithChildren
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutOffersRoute: typeof LayoutOffersRoute
  LayoutOrdersRoute: typeof LayoutOrdersRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWalletRoute: typeof LayoutWalletRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEscrowOrderIdRoute: typeof LayoutEscrowOrderIdRoute
  LayoutLegalAboutRoute: typeof LayoutLegalAboutRoute
  LayoutLegalPrivacyRoute: typeof LayoutLegalPrivacyRoute
  LayoutLegalRegulationRoute: typeof LayoutLegalRegulationRoute
  LayoutLegalTermsRoute: typeof LayoutLegalTermsRoute
  LayoutUUserIdRoute: typeof LayoutUUserIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutCategoriesRoute: LayoutCategoriesRouteWithChildren,
  LayoutHelpRoute: LayoutHelpRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRouteWithChildren,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutOffersRoute: LayoutOffersRoute,
  LayoutOrdersRoute: LayoutOrdersRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWalletRoute: LayoutWalletRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEscrowOrderIdRoute: LayoutEscrowOrderIdRoute,
  LayoutLegalAboutRoute: LayoutLegalAboutRoute,
  LayoutLegalPrivacyRoute: LayoutLegalPrivacyRoute,
  LayoutLegalRegulationRoute: LayoutLegalRegulationRoute,
  LayoutLegalTermsRoute: LayoutLegalTermsRoute,
  LayoutUUserIdRoute: LayoutUUserIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
