/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminEscrowRouteImport } from './routes/admin/escrow'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as ProtectedWalletRouteImport } from './routes/_protected/wallet'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSavedRouteImport } from './routes/_protected/saved'
import { Route as ProtectedOrdersRouteImport } from './routes/_protected/orders'
import { Route as ProtectedOffersRouteImport } from './routes/_protected/offers'
import { Route as ProtectedNotificationsRouteImport } from './routes/_protected/notifications'
import { Route as ProtectedMyListingsRouteImport } from './routes/_protected/my-listings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHelpRouteImport } from './routes/_layout/help'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as ProtectedOrdersOrderIdRouteImport } from './routes/_protected/orders.$orderId'
import { Route as ProtectedItemsCreateRouteImport } from './routes/_protected/items.create'
import { Route as ProtectedEscrowOrderIdRouteImport } from './routes/_protected/escrow.$orderId'
import { Route as LayoutUUserIdRouteImport } from './routes/_layout/u.$userId'
import { Route as LayoutLegalTermsRouteImport } from './routes/_layout/legal.terms'
import { Route as LayoutLegalRegulationRouteImport } from './routes/_layout/legal.regulation'
import { Route as LayoutLegalPrivacyRouteImport } from './routes/_layout/legal.privacy'
import { Route as LayoutLegalAboutRouteImport } from './routes/_layout/legal.about'
import { Route as LayoutItemsListingIdRouteImport } from './routes/_layout/items.$listingId'
import { Route as LayoutHelpSafetyRouteImport } from './routes/_layout/help.safety'
import { Route as LayoutHelpFaqRouteImport } from './routes/_layout/help.faq'
import { Route as LayoutHelpContactRouteImport } from './routes/_layout/help.contact'
import { Route as LayoutCategoriesSlugRouteImport } from './routes/_layout/categories.$slug'
import { Route as ProtectedItemsListingIdEditRouteImport } from './routes/_protected/items.$listingId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEscrowRoute = AdminEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ProtectedWalletRoute = ProtectedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSavedRoute = ProtectedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersRoute = ProtectedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOffersRoute = ProtectedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsRoute = ProtectedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyListingsRoute = ProtectedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => ProtectedRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHelpRoute = LayoutHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const ProtectedOrdersOrderIdRoute = ProtectedOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ProtectedOrdersRoute,
} as any)
const ProtectedItemsCreateRoute = ProtectedItemsCreateRouteImport.update({
  id: '/items/create',
  path: '/items/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEscrowOrderIdRoute = ProtectedEscrowOrderIdRouteImport.update({
  id: '/escrow/$orderId',
  path: '/escrow/$orderId',
  getParentRoute: () => ProtectedRoute,
} as any)
const LayoutUUserIdRoute = LayoutUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalTermsRoute = LayoutLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalRegulationRoute = LayoutLegalRegulationRouteImport.update({
  id: '/legal/regulation',
  path: '/legal/regulation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalPrivacyRoute = LayoutLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLegalAboutRoute = LayoutLegalAboutRouteImport.update({
  id: '/legal/about',
  path: '/legal/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsListingIdRoute = LayoutItemsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => LayoutItemsRoute,
} as any)
const LayoutHelpSafetyRoute = LayoutHelpSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => LayoutHelpRoute,
} as any)
const LayoutHelpFaqRoute = LayoutHelpFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutHelpRoute,
} as any)
const LayoutHelpContactRoute = LayoutHelpContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutHelpRoute,
} as any)
const LayoutCategoriesSlugRoute = LayoutCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutCategoriesRoute,
} as any)
const ProtectedItemsListingIdEditRoute =
  ProtectedItemsListingIdEditRouteImport.update({
    id: '/items/$listingId/edit',
    path: '/items/$listingId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof LayoutCategoriesRouteWithChildren
  '/help': typeof LayoutHelpRouteWithChildren
  '/items': typeof LayoutItemsRouteWithChildren
  '/search': typeof LayoutSearchRoute
  '/my-listings': typeof ProtectedMyListingsRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/offers': typeof ProtectedOffersRoute
  '/orders': typeof ProtectedOrdersRouteWithChildren
  '/saved': typeof ProtectedSavedRoute
  '/settings': typeof ProtectedSettingsRoute
  '/wallet': typeof ProtectedWalletRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/escrow': typeof AdminEscrowRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/search/': typeof SearchIndexRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/help/contact': typeof LayoutHelpContactRoute
  '/help/faq': typeof LayoutHelpFaqRoute
  '/help/safety': typeof LayoutHelpSafetyRoute
  '/items/$listingId': typeof LayoutItemsListingIdRoute
  '/legal/about': typeof LayoutLegalAboutRoute
  '/legal/privacy': typeof LayoutLegalPrivacyRoute
  '/legal/regulation': typeof LayoutLegalRegulationRoute
  '/legal/terms': typeof LayoutLegalTermsRoute
  '/u/$userId': typeof LayoutUUserIdRoute
  '/escrow/$orderId': typeof ProtectedEscrowOrderIdRoute
  '/items/create': typeof ProtectedItemsCreateRoute
  '/orders/$orderId': typeof ProtectedOrdersOrderIdRoute
  '/items/$listingId/edit': typeof ProtectedItemsListingIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof LayoutCategoriesRouteWithChildren
  '/help': typeof LayoutHelpRouteWithChildren
  '/items': typeof LayoutItemsRouteWithChildren
  '/search': typeof SearchIndexRoute
  '/my-listings': typeof ProtectedMyListingsRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/offers': typeof ProtectedOffersRoute
  '/orders': typeof ProtectedOrdersRouteWithChildren
  '/saved': typeof ProtectedSavedRoute
  '/settings': typeof ProtectedSettingsRoute
  '/wallet': typeof ProtectedWalletRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/escrow': typeof AdminEscrowRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/help/contact': typeof LayoutHelpContactRoute
  '/help/faq': typeof LayoutHelpFaqRoute
  '/help/safety': typeof LayoutHelpSafetyRoute
  '/items/$listingId': typeof LayoutItemsListingIdRoute
  '/legal/about': typeof LayoutLegalAboutRoute
  '/legal/privacy': typeof LayoutLegalPrivacyRoute
  '/legal/regulation': typeof LayoutLegalRegulationRoute
  '/legal/terms': typeof LayoutLegalTermsRoute
  '/u/$userId': typeof LayoutUUserIdRoute
  '/escrow/$orderId': typeof ProtectedEscrowOrderIdRoute
  '/items/create': typeof ProtectedItemsCreateRoute
  '/orders/$orderId': typeof ProtectedOrdersOrderIdRoute
  '/items/$listingId/edit': typeof ProtectedItemsListingIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/categories': typeof LayoutCategoriesRouteWithChildren
  '/_layout/help': typeof LayoutHelpRouteWithChildren
  '/_layout/items': typeof LayoutItemsRouteWithChildren
  '/_layout/search': typeof LayoutSearchRoute
  '/_protected/my-listings': typeof ProtectedMyListingsRoute
  '/_protected/notifications': typeof ProtectedNotificationsRoute
  '/_protected/offers': typeof ProtectedOffersRoute
  '/_protected/orders': typeof ProtectedOrdersRouteWithChildren
  '/_protected/saved': typeof ProtectedSavedRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/wallet': typeof ProtectedWalletRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/escrow': typeof AdminEscrowRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/search/': typeof SearchIndexRoute
  '/_layout/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/_layout/help/contact': typeof LayoutHelpContactRoute
  '/_layout/help/faq': typeof LayoutHelpFaqRoute
  '/_layout/help/safety': typeof LayoutHelpSafetyRoute
  '/_layout/items/$listingId': typeof LayoutItemsListingIdRoute
  '/_layout/legal/about': typeof LayoutLegalAboutRoute
  '/_layout/legal/privacy': typeof LayoutLegalPrivacyRoute
  '/_layout/legal/regulation': typeof LayoutLegalRegulationRoute
  '/_layout/legal/terms': typeof LayoutLegalTermsRoute
  '/_layout/u/$userId': typeof LayoutUUserIdRoute
  '/_protected/escrow/$orderId': typeof ProtectedEscrowOrderIdRoute
  '/_protected/items/create': typeof ProtectedItemsCreateRoute
  '/_protected/orders/$orderId': typeof ProtectedOrdersOrderIdRoute
  '/_protected/items/$listingId/edit': typeof ProtectedItemsListingIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/help'
    | '/items'
    | '/search'
    | '/my-listings'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/saved'
    | '/settings'
    | '/wallet'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/escrow'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/'
    | '/search/'
    | '/categories/$slug'
    | '/help/contact'
    | '/help/faq'
    | '/help/safety'
    | '/items/$listingId'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/regulation'
    | '/legal/terms'
    | '/u/$userId'
    | '/escrow/$orderId'
    | '/items/create'
    | '/orders/$orderId'
    | '/items/$listingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/help'
    | '/items'
    | '/search'
    | '/my-listings'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/saved'
    | '/settings'
    | '/wallet'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/escrow'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin'
    | '/categories/$slug'
    | '/help/contact'
    | '/help/faq'
    | '/help/safety'
    | '/items/$listingId'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/regulation'
    | '/legal/terms'
    | '/u/$userId'
    | '/escrow/$orderId'
    | '/items/create'
    | '/orders/$orderId'
    | '/items/$listingId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/_protected'
    | '/admin'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/categories'
    | '/_layout/help'
    | '/_layout/items'
    | '/_layout/search'
    | '/_protected/my-listings'
    | '/_protected/notifications'
    | '/_protected/offers'
    | '/_protected/orders'
    | '/_protected/saved'
    | '/_protected/settings'
    | '/_protected/wallet'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/escrow'
    | '/admin/moderation'
    | '/admin/orders'
    | '/_layout/'
    | '/admin/'
    | '/search/'
    | '/_layout/categories/$slug'
    | '/_layout/help/contact'
    | '/_layout/help/faq'
    | '/_layout/help/safety'
    | '/_layout/items/$listingId'
    | '/_layout/legal/about'
    | '/_layout/legal/privacy'
    | '/_layout/legal/regulation'
    | '/_layout/legal/terms'
    | '/_layout/u/$userId'
    | '/_protected/escrow/$orderId'
    | '/_protected/items/create'
    | '/_protected/orders/$orderId'
    | '/_protected/items/$listingId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/escrow': {
      id: '/admin/escrow'
      path: '/escrow'
      fullPath: '/admin/escrow'
      preLoaderRoute: typeof AdminEscrowRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_protected/wallet': {
      id: '/_protected/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof ProtectedWalletRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/saved': {
      id: '/_protected/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof ProtectedSavedRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders': {
      id: '/_protected/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedOrdersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/offers': {
      id: '/_protected/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof ProtectedOffersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications': {
      id: '/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-listings': {
      id: '/_protected/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof ProtectedMyListingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/help': {
      id: '/_layout/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof LayoutHelpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_protected/orders/$orderId': {
      id: '/_protected/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof ProtectedOrdersOrderIdRouteImport
      parentRoute: typeof ProtectedOrdersRoute
    }
    '/_protected/items/create': {
      id: '/_protected/items/create'
      path: '/items/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof ProtectedItemsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/escrow/$orderId': {
      id: '/_protected/escrow/$orderId'
      path: '/escrow/$orderId'
      fullPath: '/escrow/$orderId'
      preLoaderRoute: typeof ProtectedEscrowOrderIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_layout/u/$userId': {
      id: '/_layout/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof LayoutUUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/terms': {
      id: '/_layout/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LayoutLegalTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/regulation': {
      id: '/_layout/legal/regulation'
      path: '/legal/regulation'
      fullPath: '/legal/regulation'
      preLoaderRoute: typeof LayoutLegalRegulationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/privacy': {
      id: '/_layout/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LayoutLegalPrivacyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/legal/about': {
      id: '/_layout/legal/about'
      path: '/legal/about'
      fullPath: '/legal/about'
      preLoaderRoute: typeof LayoutLegalAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items/$listingId': {
      id: '/_layout/items/$listingId'
      path: '/$listingId'
      fullPath: '/items/$listingId'
      preLoaderRoute: typeof LayoutItemsListingIdRouteImport
      parentRoute: typeof LayoutItemsRoute
    }
    '/_layout/help/safety': {
      id: '/_layout/help/safety'
      path: '/safety'
      fullPath: '/help/safety'
      preLoaderRoute: typeof LayoutHelpSafetyRouteImport
      parentRoute: typeof LayoutHelpRoute
    }
    '/_layout/help/faq': {
      id: '/_layout/help/faq'
      path: '/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof LayoutHelpFaqRouteImport
      parentRoute: typeof LayoutHelpRoute
    }
    '/_layout/help/contact': {
      id: '/_layout/help/contact'
      path: '/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof LayoutHelpContactRouteImport
      parentRoute: typeof LayoutHelpRoute
    }
    '/_layout/categories/$slug': {
      id: '/_layout/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof LayoutCategoriesSlugRouteImport
      parentRoute: typeof LayoutCategoriesRoute
    }
    '/_protected/items/$listingId/edit': {
      id: '/_protected/items/$listingId/edit'
      path: '/items/$listingId/edit'
      fullPath: '/items/$listingId/edit'
      preLoaderRoute: typeof ProtectedItemsListingIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface LayoutCategoriesRouteChildren {
  LayoutCategoriesSlugRoute: typeof LayoutCategoriesSlugRoute
}

const LayoutCategoriesRouteChildren: LayoutCategoriesRouteChildren = {
  LayoutCategoriesSlugRoute: LayoutCategoriesSlugRoute,
}

const LayoutCategoriesRouteWithChildren =
  LayoutCategoriesRoute._addFileChildren(LayoutCategoriesRouteChildren)

interface LayoutHelpRouteChildren {
  LayoutHelpContactRoute: typeof LayoutHelpContactRoute
  LayoutHelpFaqRoute: typeof LayoutHelpFaqRoute
  LayoutHelpSafetyRoute: typeof LayoutHelpSafetyRoute
}

const LayoutHelpRouteChildren: LayoutHelpRouteChildren = {
  LayoutHelpContactRoute: LayoutHelpContactRoute,
  LayoutHelpFaqRoute: LayoutHelpFaqRoute,
  LayoutHelpSafetyRoute: LayoutHelpSafetyRoute,
}

const LayoutHelpRouteWithChildren = LayoutHelpRoute._addFileChildren(
  LayoutHelpRouteChildren,
)

interface LayoutItemsRouteChildren {
  LayoutItemsListingIdRoute: typeof LayoutItemsListingIdRoute
}

const LayoutItemsRouteChildren: LayoutItemsRouteChildren = {
  LayoutItemsListingIdRoute: LayoutItemsListingIdRoute,
}

const LayoutItemsRouteWithChildren = LayoutItemsRoute._addFileChildren(
  LayoutItemsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutCategoriesRoute: typeof LayoutCategoriesRouteWithChildren
  LayoutHelpRoute: typeof LayoutHelpRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutLegalAboutRoute: typeof LayoutLegalAboutRoute
  LayoutLegalPrivacyRoute: typeof LayoutLegalPrivacyRoute
  LayoutLegalRegulationRoute: typeof LayoutLegalRegulationRoute
  LayoutLegalTermsRoute: typeof LayoutLegalTermsRoute
  LayoutUUserIdRoute: typeof LayoutUUserIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCategoriesRoute: LayoutCategoriesRouteWithChildren,
  LayoutHelpRoute: LayoutHelpRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutLegalAboutRoute: LayoutLegalAboutRoute,
  LayoutLegalPrivacyRoute: LayoutLegalPrivacyRoute,
  LayoutLegalRegulationRoute: LayoutLegalRegulationRoute,
  LayoutLegalTermsRoute: LayoutLegalTermsRoute,
  LayoutUUserIdRoute: LayoutUUserIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ProtectedOrdersRouteChildren {
  ProtectedOrdersOrderIdRoute: typeof ProtectedOrdersOrderIdRoute
}

const ProtectedOrdersRouteChildren: ProtectedOrdersRouteChildren = {
  ProtectedOrdersOrderIdRoute: ProtectedOrdersOrderIdRoute,
}

const ProtectedOrdersRouteWithChildren = ProtectedOrdersRoute._addFileChildren(
  ProtectedOrdersRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedMyListingsRoute: typeof ProtectedMyListingsRoute
  ProtectedNotificationsRoute: typeof ProtectedNotificationsRoute
  ProtectedOffersRoute: typeof ProtectedOffersRoute
  ProtectedOrdersRoute: typeof ProtectedOrdersRouteWithChildren
  ProtectedSavedRoute: typeof ProtectedSavedRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedWalletRoute: typeof ProtectedWalletRoute
  ProtectedEscrowOrderIdRoute: typeof ProtectedEscrowOrderIdRoute
  ProtectedItemsCreateRoute: typeof ProtectedItemsCreateRoute
  ProtectedItemsListingIdEditRoute: typeof ProtectedItemsListingIdEditRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMyListingsRoute: ProtectedMyListingsRoute,
  ProtectedNotificationsRoute: ProtectedNotificationsRoute,
  ProtectedOffersRoute: ProtectedOffersRoute,
  ProtectedOrdersRoute: ProtectedOrdersRouteWithChildren,
  ProtectedSavedRoute: ProtectedSavedRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedWalletRoute: ProtectedWalletRoute,
  ProtectedEscrowOrderIdRoute: ProtectedEscrowOrderIdRoute,
  ProtectedItemsCreateRoute: ProtectedItemsCreateRoute,
  ProtectedItemsListingIdEditRoute: ProtectedItemsListingIdEditRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminEscrowRoute: typeof AdminEscrowRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminEscrowRoute: AdminEscrowRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
