/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWalletRouteImport } from './routes/_layout/wallet'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutOffersRouteImport } from './routes/_layout/offers'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutUUserIdRouteImport } from './routes/_layout/u.$userId'
import { Route as LayoutOrdersOrderIdRouteImport } from './routes/_layout/orders.$orderId'
import { Route as LayoutItemsCreateRouteImport } from './routes/_layout/items.create'
import { Route as LayoutItemsListingIdRouteImport } from './routes/_layout/items.$listingId'
import { Route as LayoutEscrowOrderIdRouteImport } from './routes/_layout/escrow.$orderId'
import { Route as LayoutAdminModerationRouteImport } from './routes/_layout/admin.moderation'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWalletRoute = LayoutWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOffersRoute = LayoutOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUUserIdRoute = LayoutUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersOrderIdRoute = LayoutOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => LayoutOrdersRoute,
} as any)
const LayoutItemsCreateRoute = LayoutItemsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutItemsRoute,
} as any)
const LayoutItemsListingIdRoute = LayoutItemsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => LayoutItemsRoute,
} as any)
const LayoutEscrowOrderIdRoute = LayoutEscrowOrderIdRouteImport.update({
  id: '/escrow/$orderId',
  path: '/escrow/$orderId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminModerationRoute = LayoutAdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/items': typeof LayoutItemsRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/wallet': typeof LayoutWalletRoute
  '/admin/moderation': typeof LayoutAdminModerationRoute
  '/escrow/$orderId': typeof LayoutEscrowOrderIdRoute
  '/items/$listingId': typeof LayoutItemsListingIdRoute
  '/items/create': typeof LayoutItemsCreateRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/u/$userId': typeof LayoutUUserIdRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/items': typeof LayoutItemsRouteWithChildren
  '/notifications': typeof LayoutNotificationsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/wallet': typeof LayoutWalletRoute
  '/': typeof LayoutIndexRoute
  '/admin/moderation': typeof LayoutAdminModerationRoute
  '/escrow/$orderId': typeof LayoutEscrowOrderIdRoute
  '/items/$listingId': typeof LayoutItemsListingIdRoute
  '/items/create': typeof LayoutItemsCreateRoute
  '/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/u/$userId': typeof LayoutUUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/items': typeof LayoutItemsRouteWithChildren
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/offers': typeof LayoutOffersRoute
  '/_layout/orders': typeof LayoutOrdersRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/wallet': typeof LayoutWalletRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/moderation': typeof LayoutAdminModerationRoute
  '/_layout/escrow/$orderId': typeof LayoutEscrowOrderIdRoute
  '/_layout/items/$listingId': typeof LayoutItemsListingIdRoute
  '/_layout/items/create': typeof LayoutItemsCreateRoute
  '/_layout/orders/$orderId': typeof LayoutOrdersOrderIdRoute
  '/_layout/u/$userId': typeof LayoutUUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/settings'
    | '/wallet'
    | '/admin/moderation'
    | '/escrow/$orderId'
    | '/items/$listingId'
    | '/items/create'
    | '/orders/$orderId'
    | '/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/notifications'
    | '/offers'
    | '/orders'
    | '/settings'
    | '/wallet'
    | '/'
    | '/admin/moderation'
    | '/escrow/$orderId'
    | '/items/$listingId'
    | '/items/create'
    | '/orders/$orderId'
    | '/u/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/landing'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/notifications'
    | '/_layout/offers'
    | '/_layout/orders'
    | '/_layout/settings'
    | '/_layout/wallet'
    | '/_layout/'
    | '/_layout/admin/moderation'
    | '/_layout/escrow/$orderId'
    | '/_layout/items/$listingId'
    | '/_layout/items/create'
    | '/_layout/orders/$orderId'
    | '/_layout/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wallet': {
      id: '/_layout/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof LayoutWalletRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offers': {
      id: '/_layout/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof LayoutOffersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/u/$userId': {
      id: '/_layout/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof LayoutUUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders/$orderId': {
      id: '/_layout/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof LayoutOrdersOrderIdRouteImport
      parentRoute: typeof LayoutOrdersRoute
    }
    '/_layout/items/create': {
      id: '/_layout/items/create'
      path: '/create'
      fullPath: '/items/create'
      preLoaderRoute: typeof LayoutItemsCreateRouteImport
      parentRoute: typeof LayoutItemsRoute
    }
    '/_layout/items/$listingId': {
      id: '/_layout/items/$listingId'
      path: '/$listingId'
      fullPath: '/items/$listingId'
      preLoaderRoute: typeof LayoutItemsListingIdRouteImport
      parentRoute: typeof LayoutItemsRoute
    }
    '/_layout/escrow/$orderId': {
      id: '/_layout/escrow/$orderId'
      path: '/escrow/$orderId'
      fullPath: '/escrow/$orderId'
      preLoaderRoute: typeof LayoutEscrowOrderIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/moderation': {
      id: '/_layout/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof LayoutAdminModerationRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminModerationRoute: typeof LayoutAdminModerationRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminModerationRoute: LayoutAdminModerationRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutItemsRouteChildren {
  LayoutItemsListingIdRoute: typeof LayoutItemsListingIdRoute
  LayoutItemsCreateRoute: typeof LayoutItemsCreateRoute
}

const LayoutItemsRouteChildren: LayoutItemsRouteChildren = {
  LayoutItemsListingIdRoute: LayoutItemsListingIdRoute,
  LayoutItemsCreateRoute: LayoutItemsCreateRoute,
}

const LayoutItemsRouteWithChildren = LayoutItemsRoute._addFileChildren(
  LayoutItemsRouteChildren,
)

interface LayoutOrdersRouteChildren {
  LayoutOrdersOrderIdRoute: typeof LayoutOrdersOrderIdRoute
}

const LayoutOrdersRouteChildren: LayoutOrdersRouteChildren = {
  LayoutOrdersOrderIdRoute: LayoutOrdersOrderIdRoute,
}

const LayoutOrdersRouteWithChildren = LayoutOrdersRoute._addFileChildren(
  LayoutOrdersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRouteWithChildren
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutOffersRoute: typeof LayoutOffersRoute
  LayoutOrdersRoute: typeof LayoutOrdersRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWalletRoute: typeof LayoutWalletRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEscrowOrderIdRoute: typeof LayoutEscrowOrderIdRoute
  LayoutUUserIdRoute: typeof LayoutUUserIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRouteWithChildren,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutOffersRoute: LayoutOffersRoute,
  LayoutOrdersRoute: LayoutOrdersRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWalletRoute: LayoutWalletRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEscrowOrderIdRoute: LayoutEscrowOrderIdRoute,
  LayoutUUserIdRoute: LayoutUUserIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
