// This file is auto-generated by @hey-api/openapi-ts

export const AdminAuditLogReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        admin_id: {
            type: 'string',
            format: 'uuid',
            title: 'Admin Id'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        target_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Type'
        },
        target_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Id'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'admin_id', 'action', 'created_at'],
    title: 'AdminAuditLogRead'
} as const;

export const AdminAuditTrailResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/AdminAuditLogRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['items', 'total', 'skip', 'limit'],
    title: 'AdminAuditTrailResponse'
} as const;

export const AvailabilityOutSchema = {
    properties: {
        available: {
            type: 'boolean',
            title: 'Available'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        services: {
            items: {
                '$ref': '#/components/schemas/ServiceOut'
            },
            type: 'array',
            title: 'Services',
            default: []
        }
    },
    type: 'object',
    required: ['available'],
    title: 'AvailabilityOut'
} as const;

export const Body_login_api_v1_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_api_v1_auth_login_post'
} as const;

export const Body_reject_listing_route_api_v1_admin_listings__listing_id__reject_postSchema = {
    properties: {
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    title: 'Body_reject_listing_route_api_v1_admin_listings__listing_id__reject_post'
} as const;

export const Body_upload_listing_image_api_v1_listings__listing_id__images_postSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_listing_image_api_v1_listings__listing_id__images_post'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic',
    description: 'Response body for listing categories.'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'CategoryCreate',
    description: 'Request body for creating a category.'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'id', 'created_at'],
    title: 'CategoryPublic',
    description: 'Category API response (basic).'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        icon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Url'
        }
    },
    type: 'object',
    title: 'CategoryUpdate',
    description: 'Request body for updating a category.'
} as const;

export const ChangePasswordRequestSchema = {
    properties: {
        current_password: {
            type: 'string',
            title: 'Current Password',
            description: 'Mật khẩu hiện tại'
        },
        new_password: {
            type: 'string',
            minLength: 12,
            title: 'New Password',
            description: 'Mật khẩu mới: 12+ ký tự, 1 in hoa, 1 thường, 1 số, 1 ký tự đặc biệt'
        },
        confirm_password: {
            type: 'string',
            title: 'Confirm Password',
            description: 'Xác nhận mật khẩu mới'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password', 'confirm_password'],
    title: 'ChangePasswordRequest',
    description: 'Dữ liệu gửi lên khi đổi mật khẩu'
} as const;

export const ChatConversationReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        listing_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Listing Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        participant_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Participant Ids'
        },
        messages_count: {
            type: 'integer',
            title: 'Messages Count'
        },
        last_message: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ChatMessageRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        listing: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ListingWithImages'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'participant_ids', 'messages_count'],
    title: 'ChatConversationRead'
} as const;

export const ChatMessageCreateSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ChatMessageCreate'
} as const;

export const ChatMessageReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        sender_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sender Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'conversation_id', 'sender_id', 'content', 'created_at'],
    title: 'ChatMessageRead'
} as const;

export const ConditionGradeSchema = {
    type: 'string',
    enum: ['brand_new', 'like_new', 'good', 'fair', 'poor'],
    title: 'ConditionGrade',
    description: 'Condition grade of a product.'
} as const;

export const CreateAccountResponseSchema = {
    properties: {
        account_id: {
            type: 'string',
            title: 'Account Id'
        },
        onboarding_url: {
            type: 'string',
            title: 'Onboarding Url'
        }
    },
    type: 'object',
    required: ['account_id', 'onboarding_url'],
    title: 'CreateAccountResponse'
} as const;

export const DeliveryAgainRequestSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        }
    },
    type: 'object',
    required: ['order_id'],
    title: 'DeliveryAgainRequest'
} as const;

export const DepositRequestSchema = {
    properties: {
        amount: {
            type: 'integer',
            maximum: 50000000,
            minimum: 10000,
            title: 'Amount',
            description: 'Amount in VND'
        }
    },
    type: 'object',
    required: ['amount'],
    title: 'DepositRequest'
} as const;

export const DepositResponseSchema = {
    properties: {
        client_secret: {
            type: 'string',
            title: 'Client Secret'
        },
        payment_intent_id: {
            type: 'string',
            title: 'Payment Intent Id'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        }
    },
    type: 'object',
    required: ['client_secret', 'payment_intent_id', 'amount'],
    title: 'DepositResponse'
} as const;

export const DisputeCreateSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        reason: {
            type: 'string',
            maxLength: 2000,
            minLength: 10,
            title: 'Reason'
        },
        evidence_images: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 5,
            title: 'Evidence Images',
            default: []
        }
    },
    type: 'object',
    required: ['order_id', 'reason'],
    title: 'DisputeCreate',
    description: 'Create dispute request.'
} as const;

export const DisputeEvidenceReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        dispute_id: {
            type: 'string',
            format: 'uuid',
            title: 'Dispute Id'
        },
        uploaded_by: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaded By'
        },
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'dispute_id', 'uploaded_by', 'image_url', 'created_at'],
    title: 'DisputeEvidenceRead'
} as const;

export const DisputeReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        raised_by: {
            type: 'string',
            format: 'uuid',
            title: 'Raised By'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        resolved_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolved By'
        },
        resolution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution'
        },
        admin_notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admin Notes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        resolved_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolved At'
        },
        evidence: {
            items: {
                '$ref': '#/components/schemas/DisputeEvidenceRead'
            },
            type: 'array',
            title: 'Evidence',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'order_id', 'raised_by', 'reason', 'status', 'resolved_by', 'resolution', 'admin_notes', 'created_at', 'resolved_at'],
    title: 'DisputeRead'
} as const;

export const DistrictOutSchema = {
    properties: {
        district_id: {
            type: 'integer',
            title: 'District Id'
        },
        district_name: {
            type: 'string',
            title: 'District Name'
        }
    },
    type: 'object',
    required: ['district_id', 'district_name'],
    title: 'DistrictOut'
} as const;

export const EscrowReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        buyer_wallet_id: {
            type: 'string',
            format: 'uuid',
            title: 'Buyer Wallet Id'
        },
        seller_wallet_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Wallet Id'
        },
        funded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Funded At'
        },
        released_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Released At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'order_id', 'amount', 'status', 'buyer_wallet_id', 'seller_wallet_id', 'funded_at', 'released_at', 'created_at', 'updated_at'],
    title: 'EscrowRead',
    description: 'Escrow information response (simplified).'
} as const;

export const FeeOutSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        service_fee: {
            type: 'integer',
            title: 'Service Fee'
        },
        insurance_fee: {
            type: 'integer',
            title: 'Insurance Fee'
        },
        vat: {
            type: 'integer',
            title: 'Vat'
        }
    },
    type: 'object',
    required: ['total', 'service_fee', 'insurance_fee', 'vat'],
    title: 'FeeOut'
} as const;

export const FeeRequestSchema = {
    properties: {
        to_district_id: {
            type: 'integer',
            title: 'To District Id'
        },
        to_ward_code: {
            type: 'string',
            title: 'To Ward Code'
        },
        weight_grams: {
            type: 'integer',
            title: 'Weight Grams',
            default: 500
        },
        insurance_value: {
            type: 'integer',
            title: 'Insurance Value',
            default: 0
        }
    },
    type: 'object',
    required: ['to_district_id', 'to_ward_code'],
    title: 'FeeRequest'
} as const;

export const FollowedSellerCollectionSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/FollowedSellerItem'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['items', 'total', 'skip', 'limit'],
    title: 'FollowedSellerCollection'
} as const;

export const FollowedSellerItemSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        seller: {
            '$ref': '#/components/schemas/UserPublic'
        }
    },
    type: 'object',
    required: ['created_at', 'seller'],
    title: 'FollowedSellerItem'
} as const;

export const ForgotPasswordRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ForgotPasswordRequest',
    description: 'Dữ liệu gửi lên khi quên mật khẩu'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ListingCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 5,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Price'
        },
        is_negotiable: {
            type: 'boolean',
            title: 'Is Negotiable',
            default: true
        },
        condition_grade: {
            '$ref': '#/components/schemas/ConditionGrade'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['title', 'price', 'condition_grade', 'category_id'],
    title: 'ListingCreate'
} as const;

export const ListingImageReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'listing_id', 'image_url', 'is_primary', 'created_at'],
    title: 'ListingImageRead',
    description: 'Response schema for listing images'
} as const;

export const ListingPaginatedSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ListingWithImages'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['total', 'skip', 'limit'],
    title: 'ListingPaginated',
    description: 'Response schema for paginated listings'
} as const;

export const ListingReadSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 5,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Price'
        },
        is_negotiable: {
            type: 'boolean',
            title: 'Is Negotiable',
            default: true
        },
        condition_grade: {
            '$ref': '#/components/schemas/ConditionGrade'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        status: {
            '$ref': '#/components/schemas/ListingStatus'
        },
        rejection_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rejection Reason'
        },
        view_count: {
            type: 'integer',
            title: 'View Count',
            default: 0
        },
        save_count: {
            type: 'integer',
            title: 'Save Count',
            default: 0
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        location_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Summary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'price', 'condition_grade', 'category_id', 'id', 'seller_id', 'status', 'created_at', 'updated_at'],
    title: 'ListingRead'
} as const;

export const ListingStatusSchema = {
    type: 'string',
    enum: ['pending', 'active', 'sold', 'hidden', 'rejected'],
    title: 'ListingStatus',
    description: 'Status of a listing.'
} as const;

export const ListingUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        is_negotiable: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Negotiable'
        },
        condition_grade: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ConditionGrade'
                },
                {
                    type: 'null'
                }
            ]
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ListingStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ListingUpdate'
} as const;

export const ListingWithImagesSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 5,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Price'
        },
        is_negotiable: {
            type: 'boolean',
            title: 'Is Negotiable',
            default: true
        },
        condition_grade: {
            '$ref': '#/components/schemas/ConditionGrade'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        status: {
            '$ref': '#/components/schemas/ListingStatus'
        },
        rejection_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rejection Reason'
        },
        view_count: {
            type: 'integer',
            title: 'View Count',
            default: 0
        },
        save_count: {
            type: 'integer',
            title: 'Save Count',
            default: 0
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        location_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Summary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/ListingImageRead'
            },
            type: 'array',
            title: 'Images',
            default: []
        },
        seller_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seller Name'
        },
        seller_avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seller Avatar Url'
        }
    },
    type: 'object',
    required: ['title', 'price', 'condition_grade', 'category_id', 'id', 'seller_id', 'status', 'created_at', 'updated_at'],
    title: 'ListingWithImages',
    description: 'Response schema for listing with images'
} as const;

export const MessageResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'MessageResponse',
    description: 'Generic response message.'
} as const;

export const NotificationReadSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        type: {
            '$ref': '#/components/schemas/NotificationType'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['user_id', 'type', 'title', 'message', 'id', 'is_read', 'created_at'],
    title: 'NotificationRead'
} as const;

export const NotificationTypeSchema = {
    type: 'string',
    enum: ['listing_approved', 'listing_rejected', 'offer_received', 'offer_accepted', 'offer_rejected', 'offer_countered', 'offer_expired', 'order_created', 'order_shipping', 'order_delivered', 'order_completed', 'order_accepted', 'order_auto_completed', 'order_cancelled', 'order_status_updated', 'dispute_opened', 'dispute_resolved', 'shipping_created', 'shipping_delivered', 'return_requested', 'return_confirmed', 'review_received', 'wallet_balance_updated', 'wallet_locked', 'wallet_released'],
    title: 'NotificationType',
    description: 'Type of notification.'
} as const;

export const NotificationsPaginatedSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/NotificationRead'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: ['items', 'total', 'page', 'page_size', 'total_pages'],
    title: 'NotificationsPaginated',
    description: 'Phản hồi thông báo có phân trang'
} as const;

export const OfferCreateSchema = {
    properties: {
        offer_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Offer Price',
            description: 'The price offered by the buyer'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id',
            description: 'The listing ID to make an offer on'
        }
    },
    type: 'object',
    required: ['offer_price', 'listing_id'],
    title: 'OfferCreate'
} as const;

export const OfferReadSchema = {
    properties: {
        offer_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Offer Price',
            description: 'The price offered by the buyer'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        buyer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Buyer Id'
        },
        status: {
            '$ref': '#/components/schemas/OfferStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        order_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order Id'
        }
    },
    type: 'object',
    required: ['offer_price', 'id', 'listing_id', 'buyer_id', 'status', 'created_at', 'updated_at'],
    title: 'OfferRead'
} as const;

export const OfferStatusSchema = {
    type: 'string',
    enum: ['pending', 'accepted', 'rejected', 'countered', 'expired'],
    title: 'OfferStatus',
    description: 'Status of an offer (negotiation).'
} as const;

export const OfferStatusUpdateSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/OfferStatus',
            description: 'New status for the offer (ACCEPTED, REJECTED, COUNTERED)'
        },
        offer_price: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offer Price'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'OfferStatusUpdate'
} as const;

export const OnboardingStatusResponseSchema = {
    properties: {
        account_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        onboarding_complete: {
            type: 'boolean',
            title: 'Onboarding Complete'
        },
        account_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Status'
        },
        charges_enabled: {
            type: 'boolean',
            title: 'Charges Enabled'
        },
        payouts_enabled: {
            type: 'boolean',
            title: 'Payouts Enabled'
        }
    },
    type: 'object',
    required: ['account_id', 'onboarding_complete', 'account_status', 'charges_enabled', 'payouts_enabled'],
    title: 'OnboardingStatusResponse'
} as const;

export const OrderDirectCreateSchema = {
    properties: {
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        payment_method: {
            '$ref': '#/components/schemas/PaymentMethod',
            default: 'wallet'
        },
        shipping_address: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShippingAddressInput'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['listing_id'],
    title: 'OrderDirectCreate'
} as const;

export const OrderEventReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        event_type: {
            type: 'string',
            title: 'Event Type'
        },
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        },
        actor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'order_id', 'event_type', 'created_at'],
    title: 'OrderEventRead'
} as const;

export const OrderReadSchema = {
    properties: {
        final_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$',
            title: 'Final Price'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        buyer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Buyer Id'
        },
        seller_id: {
            type: 'string',
            format: 'uuid',
            title: 'Seller Id'
        },
        listing_id: {
            type: 'string',
            format: 'uuid',
            title: 'Listing Id'
        },
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        payment_method: {
            '$ref': '#/components/schemas/PaymentMethod',
            default: 'wallet'
        },
        shipping_provider: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Provider'
        },
        shipping_service_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Service Type'
        },
        shipping_fee: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Fee'
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        expected_delivery_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Delivery At'
        },
        delivered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivered At'
        },
        shipping_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Name'
        },
        shipping_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Phone'
        },
        shipping_province: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Province'
        },
        shipping_district: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping District'
        },
        shipping_ward: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Ward'
        },
        shipping_address_detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Address Detail'
        },
        shipping_note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Note'
        },
        shipping_province_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Province Id'
        },
        shipping_district_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping District Id'
        },
        shipping_ward_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Ward Code'
        },
        offer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offer Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['final_price', 'id', 'buyer_id', 'seller_id', 'listing_id', 'status', 'created_at', 'updated_at'],
    title: 'OrderRead'
} as const;

export const OrderStatusSchema = {
    type: 'string',
    enum: ['pending', 'shipping', 'delivered', 'returning', 'returned', 'completed', 'cancelled', 'disputed'],
    title: 'OrderStatus',
    description: 'Status of an order.'
} as const;

export const OrderStatusUpdateSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'OrderStatusUpdate'
} as const;

export const PaymentMethodSchema = {
    type: 'string',
    enum: ['wallet', 'cod'],
    title: 'PaymentMethod',
    description: 'Phương thức thanh toán.'
} as const;

export const PriceBandReadSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        min_price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Price'
        },
        max_price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Price'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['label', 'min_price', 'max_price', 'count'],
    title: 'PriceBandRead'
} as const;

export const ProvinceOutSchema = {
    properties: {
        province_id: {
            type: 'integer',
            title: 'Province Id'
        },
        province_name: {
            type: 'string',
            title: 'Province Name'
        }
    },
    type: 'object',
    required: ['province_id', 'province_name'],
    title: 'ProvinceOut'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest',
    description: 'Dữ liệu gửi lên khi Access Token hết hạn'
} as const;

export const ResendVerificationRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'ResendVerificationRequest',
    description: 'Dữ liệu gửi lên khi gửi lại email xác minh'
} as const;

export const ResetPasswordRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            minLength: 12,
            title: 'New Password',
            description: 'Mật khẩu mới: 12+ ký tự, 1 in hoa, 1 thường, 1 số, 1 ký tự đặc biệt'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'ResetPasswordRequest',
    description: 'Dữ liệu gửi lên khi đặt lại mật khẩu'
} as const;

export const ResolveEscrowRequestSchema = {
    properties: {
        result: {
            type: 'string',
            enum: ['release', 'refund'],
            title: 'Result',
            description: 'release: transfer to seller, refund: return funds to buyer'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note',
            description: 'Optional admin note'
        }
    },
    type: 'object',
    required: ['result'],
    title: 'ResolveEscrowRequest',
    description: 'Admin resolution for disputed escrow.'
} as const;

export const ReturnOrderRequestSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['order_id'],
    title: 'ReturnOrderRequest'
} as const;

export const ReturnReasonSchema = {
    type: 'string',
    enum: ['wrong_item', 'defective', 'damaged', 'not_as_described', 'fake', 'no_longer_needed'],
    title: 'ReturnReason'
} as const;

export const ReturnRequestCreateSchema = {
    properties: {
        order_id: {
            type: 'string',
            title: 'Order Id'
        },
        reason: {
            '$ref': '#/components/schemas/ReturnReason'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        images: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Images',
            default: []
        }
    },
    type: 'object',
    required: ['order_id', 'reason'],
    title: 'ReturnRequestCreate'
} as const;

export const ReturnRespondSchema = {
    properties: {
        approve: {
            type: 'boolean',
            title: 'Approve'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['approve'],
    title: 'ReturnRespond'
} as const;

export const ReturnShipInputSchema = {
    properties: {
        return_tracking_number: {
            type: 'string',
            title: 'Return Tracking Number'
        },
        return_carrier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Return Carrier'
        }
    },
    type: 'object',
    required: ['return_tracking_number'],
    title: 'ReturnShipInput'
} as const;

export const ReviewCreateSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['order_id', 'rating'],
    title: 'ReviewCreate'
} as const;

export const ReviewReadSchema = {
    properties: {
        order_id: {
            type: 'string',
            format: 'uuid',
            title: 'Order Id'
        },
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        reviewer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewer Id'
        },
        reviewee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewee Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['order_id', 'rating', 'id', 'reviewer_id', 'reviewee_id', 'created_at'],
    title: 'ReviewRead'
} as const;

export const ReviewSummaryOnlyReadSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        average_rating: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average Rating'
        },
        total_reviews: {
            type: 'integer',
            title: 'Total Reviews'
        },
        rating_breakdown: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Rating Breakdown'
        }
    },
    type: 'object',
    required: ['user_id', 'average_rating', 'total_reviews', 'rating_breakdown'],
    title: 'ReviewSummaryOnlyRead'
} as const;

export const ReviewSummaryReadSchema = {
    properties: {
        average_rating: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average Rating'
        },
        total_reviews: {
            type: 'integer',
            title: 'Total Reviews'
        },
        rating_breakdown: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Rating Breakdown'
        }
    },
    type: 'object',
    required: ['average_rating', 'total_reviews', 'rating_breakdown'],
    title: 'ReviewSummaryRead'
} as const;

export const SavedListingCollectionSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/SavedListingItem'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['items', 'total', 'skip', 'limit'],
    title: 'SavedListingCollection'
} as const;

export const SavedListingItemSchema = {
    properties: {
        saved_at: {
            type: 'string',
            format: 'date-time',
            title: 'Saved At'
        },
        listing: {
            '$ref': '#/components/schemas/ListingWithImages'
        }
    },
    type: 'object',
    required: ['saved_at', 'listing'],
    title: 'SavedListingItem'
} as const;

export const SellerShopProfileReadSchema = {
    properties: {
        seller: {
            '$ref': '#/components/schemas/UserPublic'
        },
        total_active_listings: {
            type: 'integer',
            title: 'Total Active Listings'
        },
        recent_listings: {
            items: {
                '$ref': '#/components/schemas/ListingWithImages'
            },
            type: 'array',
            title: 'Recent Listings'
        },
        review_summary: {
            '$ref': '#/components/schemas/ReviewSummaryRead'
        }
    },
    type: 'object',
    required: ['seller', 'total_active_listings', 'recent_listings', 'review_summary'],
    title: 'SellerShopProfileRead'
} as const;

export const ServiceOutSchema = {
    properties: {
        service_id: {
            type: 'integer',
            title: 'Service Id'
        },
        short_name: {
            type: 'string',
            title: 'Short Name'
        },
        service_type_id: {
            type: 'integer',
            title: 'Service Type Id'
        }
    },
    type: 'object',
    required: ['service_id', 'short_name', 'service_type_id'],
    title: 'ServiceOut'
} as const;

export const ShipOrderInputSchema = {
    properties: {
        tracking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        shipping_provider: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shipping Provider'
        }
    },
    type: 'object',
    title: 'ShipOrderInput'
} as const;

export const ShippingAddressInputSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        phone: {
            type: 'string',
            maxLength: 20,
            title: 'Phone'
        },
        province: {
            type: 'string',
            maxLength: 100,
            title: 'Province'
        },
        district: {
            type: 'string',
            maxLength: 100,
            title: 'District'
        },
        ward: {
            type: 'string',
            maxLength: 100,
            title: 'Ward'
        },
        address_detail: {
            type: 'string',
            maxLength: 255,
            title: 'Address Detail'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        province_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province Id'
        },
        district_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'District Id'
        },
        ward_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ward Code'
        }
    },
    type: 'object',
    required: ['name', 'phone', 'province', 'district', 'ward', 'address_detail'],
    title: 'ShippingAddressInput'
} as const;

export const ShippingOrderOutSchema = {
    properties: {
        order_code: {
            type: 'string',
            title: 'Order Code'
        },
        expected_delivery_time: {
            type: 'string',
            title: 'Expected Delivery Time'
        },
        total_fee: {
            type: 'integer',
            title: 'Total Fee'
        },
        tracking_url: {
            type: 'string',
            title: 'Tracking Url',
            default: ''
        }
    },
    type: 'object',
    required: ['order_code', 'expected_delivery_time', 'total_fee'],
    title: 'ShippingOrderOut'
} as const;

export const ShippingOrderRequestSchema = {
    properties: {
        order_id: {
            type: 'string',
            title: 'Order Id'
        },
        to_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To Name'
        },
        to_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To Phone'
        },
        to_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To Address'
        },
        to_ward_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To Ward Code'
        },
        to_district_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To District Id'
        },
        to_province_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'To Province Id'
        },
        weight_grams: {
            type: 'integer',
            title: 'Weight Grams',
            default: 500
        },
        insurance_value: {
            type: 'integer',
            title: 'Insurance Value',
            default: 0
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        service_type_id: {
            type: 'integer',
            title: 'Service Type Id',
            default: 2
        }
    },
    type: 'object',
    required: ['order_id'],
    title: 'ShippingOrderRequest'
} as const;

export const StaticContentCollectionSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/StaticContentRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'StaticContentCollection'
} as const;

export const StaticContentReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        locale: {
            type: 'string',
            title: 'Locale'
        },
        version: {
            type: 'integer',
            title: 'Version'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'key', 'title', 'body', 'locale', 'version', 'created_at', 'updated_at'],
    title: 'StaticContentRead'
} as const;

export const TokenResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        user: {
            '$ref': '#/components/schemas/UserPrivate'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'user'],
    title: 'TokenResponse',
    description: 'Dữ liệu Backend trả về khi Đăng nhập thành công'
} as const;

export const TransactionListResponseSchema = {
    properties: {
        transactions: {
            items: {
                '$ref': '#/components/schemas/TransactionRead'
            },
            type: 'array',
            title: 'Transactions'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['transactions', 'total'],
    title: 'TransactionListResponse',
    description: 'Paginated transaction list response.'
} as const;

export const TransactionReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        wallet_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wallet Id'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        order_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order Id'
        },
        escrow_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Escrow Id'
        },
        payment_gateway_ref: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Gateway Ref'
        },
        bank_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Code'
        },
        bank_account: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Account'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'completed'
        },
        balance_before: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Balance Before'
        },
        balance_after: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Balance After'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'wallet_id', 'amount', 'type', 'description', 'order_id', 'escrow_id', 'balance_before', 'balance_after', 'created_at'],
    title: 'TransactionRead',
    description: 'Wallet transaction response.'
} as const;

export const UserMeSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        is_email_verified: {
            type: 'boolean',
            title: 'Is Email Verified'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        rating_avg: {
            type: 'number',
            title: 'Rating Avg',
            default: 0
        },
        rating_count: {
            type: 'integer',
            title: 'Rating Count',
            default: 0
        },
        trust_score: {
            type: 'number',
            title: 'Trust Score',
            default: 0
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'is_active', 'is_email_verified', 'role', 'created_at', 'updated_at'],
    title: 'UserMe',
    description: 'Current user profile response'
} as const;

export const UserPrivateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        province: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province'
        },
        district: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'District'
        },
        ward: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ward'
        },
        address_detail: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address Detail'
        },
        is_phone_verified: {
            type: 'boolean',
            title: 'Is Phone Verified',
            default: false
        },
        is_email_verified: {
            type: 'boolean',
            title: 'Is Email Verified',
            default: false
        },
        shop_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Name'
        },
        shop_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Description'
        },
        shop_verified: {
            type: 'boolean',
            title: 'Shop Verified',
            default: false
        },
        shop_response_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Response Time',
            description: 'Estimated response time in minutes'
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        },
        follower_count: {
            type: 'integer',
            title: 'Follower Count',
            default: 0
        },
        following_count: {
            type: 'integer',
            title: 'Following Count',
            default: 0
        },
        sales_count: {
            type: 'integer',
            title: 'Sales Count',
            default: 0
        },
        trust_score: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,4}|(?=[\\d.]{1,6}0*$)\\d{0,4}\\.\\d{0,1}0*$)',
            title: 'Trust Score',
            default: '0.0'
        },
        rating_avg: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*(?:\\d{0,1}|(?=[\\d.]{1,4}0*$)\\d{0,1}\\.\\d{0,2}0*$)',
            title: 'Rating Avg',
            default: '0.00'
        },
        rating_count: {
            type: 'integer',
            title: 'Rating Count',
            default: 0
        },
        completed_orders: {
            type: 'integer',
            title: 'Completed Orders',
            default: 0
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'user'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'id', 'created_at', 'updated_at'],
    title: 'UserPrivate',
    description: 'Private user profile (full info for authenticated user).'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        trust_score: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Trust Score'
        },
        rating_avg: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Rating Avg'
        },
        rating_count: {
            type: 'integer',
            title: 'Rating Count'
        },
        completed_orders: {
            type: 'integer',
            title: 'Completed Orders'
        },
        shop_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Name'
        },
        shop_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Description'
        },
        shop_verified: {
            type: 'boolean',
            title: 'Shop Verified',
            default: false
        },
        follower_count: {
            type: 'integer',
            title: 'Follower Count',
            default: 0
        },
        sales_count: {
            type: 'integer',
            title: 'Sales Count',
            default: 0
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'full_name', 'trust_score', 'rating_avg', 'rating_count', 'completed_orders', 'created_at'],
    title: 'UserPublic',
    description: 'Public user profile (minimal info for other users).'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password',
            description: 'Password must be at least 8 characters'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        }
    },
    type: 'object',
    required: ['email', 'full_name', 'password'],
    title: 'UserRegister',
    description: 'Request body for user registration (sign up).'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['user', 'admin'],
    title: 'UserRole',
    description: 'User roles in the system.'
} as const;

export const UserStatusUpdateSchema = {
    properties: {
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['is_active'],
    title: 'UserStatusUpdate',
    description: 'Update user status'
} as const;

export const UserUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        province: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Province'
        },
        district: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'District'
        },
        ward: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ward'
        },
        address_detail: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address Detail'
        },
        shop_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Name'
        },
        shop_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Description'
        },
        shop_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Verified'
        },
        shop_response_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Response Time'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Request body for updating user profile.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Response body for listing users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerifyEmailRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'VerifyEmailRequest',
    description: 'Dữ liệu gửi lên khi xác minh email'
} as const;

export const WalletReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Balance'
        },
        locked_balance: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Locked Balance'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'balance', 'locked_balance', 'created_at', 'updated_at'],
    title: 'WalletRead',
    description: 'Wallet information response.'
} as const;

export const WalletTopupRequestSchema = {
    properties: {
        amount: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 10000000,
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Amount',
            description: 'Amount to add (max 10,000,000 VND)'
        }
    },
    type: 'object',
    required: ['amount'],
    title: 'WalletTopupRequest',
    description: 'Request body for demo topup.'
} as const;

export const WardOutSchema = {
    properties: {
        ward_code: {
            type: 'string',
            title: 'Ward Code'
        },
        ward_name: {
            type: 'string',
            title: 'Ward Name'
        }
    },
    type: 'object',
    required: ['ward_code', 'ward_name'],
    title: 'WardOut'
} as const;

export const WithdrawRequestSchema = {
    properties: {
        amount: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Amount'
        }
    },
    type: 'object',
    required: ['amount'],
    title: 'WithdrawRequest'
} as const;

export const WithdrawResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['id', 'amount', 'status', 'message'],
    title: 'WithdrawResponse'
} as const;