// This file is auto-generated by @hey-api/openapi-ts

export type AdminAuditLogRead = {
    id: string;
    admin_id: string;
    action: string;
    target_type?: (string | null);
    target_id?: (string | null);
    note?: (string | null);
    created_at: string;
};

export type AdminAuditTrailResponse = {
    items: Array<AdminAuditLogRead>;
    total: number;
    skip: number;
    limit: number;
};

export type AvailabilityOut = {
    available: boolean;
    message?: string;
    services?: Array<ServiceOut>;
};

export type Body_login_api_v1_auth_login_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_reject_listing_route_api_v1_admin_listings__listing_id__reject_post = {
    reason?: (string | null);
};

export type Body_upload_listing_image_api_v1_listings__listing_id__images_post = {
    file: string;
};

/**
 * Response body for listing categories.
 */
export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

/**
 * Request body for creating a category.
 */
export type CategoryCreate = {
    name: string;
    slug: string;
    icon_url?: (string | null);
};

/**
 * Category API response (basic).
 */
export type CategoryPublic = {
    name: string;
    slug: string;
    icon_url?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Request body for updating a category.
 */
export type CategoryUpdate = {
    name?: (string | null);
    slug?: (string | null);
    icon_url?: (string | null);
};

/**
 * Dữ liệu gửi lên khi đổi mật khẩu
 */
export type ChangePasswordRequest = {
    /**
     * Mật khẩu hiện tại
     */
    current_password: string;
    /**
     * Mật khẩu mới: 12+ ký tự, 1 in hoa, 1 thường, 1 số, 1 ký tự đặc biệt
     */
    new_password: string;
    /**
     * Xác nhận mật khẩu mới
     */
    confirm_password: string;
};

export type ChatConversationRead = {
    id: string;
    listing_id?: (string | null);
    created_at: string;
    participant_ids: Array<(string)>;
    messages_count: number;
    last_message?: (ChatMessageRead | null);
    listing?: (ListingWithImages | null);
};

export type ChatMessageCreate = {
    content: string;
};

export type ChatMessageRead = {
    id: string;
    conversation_id: string;
    sender_id: string;
    content: string;
    created_at: string;
};

/**
 * Condition grade of a product.
 */
export type ConditionGrade = 'brand_new' | 'like_new' | 'good' | 'fair' | 'poor';

/**
 * Condition grade of a product.
 */
export const ConditionGrade = {
    BRAND_NEW: 'brand_new',
    LIKE_NEW: 'like_new',
    GOOD: 'good',
    FAIR: 'fair',
    POOR: 'poor'
} as const;

export type CreateAccountResponse = {
    account_id: string;
    onboarding_url: string;
};

export type DeliveryAgainRequest = {
    order_id: string;
};

export type DepositRequest = {
    /**
     * Amount in VND
     */
    amount: number;
};

export type DepositResponse = {
    client_secret: string;
    payment_intent_id: string;
    amount: number;
};

export type DistrictOut = {
    district_id: number;
    district_name: string;
};

/**
 * Escrow information response.
 */
export type EscrowRead = {
    id: string;
    order_id: string;
    amount: string;
    status: string;
    buyer_wallet_id: string;
    seller_wallet_id: string;
    dispute_reason: (string | null);
    dispute_opened_at: (string | null);
    admin_resolved_by: (string | null);
    admin_notes: (string | null);
    resolution_reason: (string | null);
    resolved_at: (string | null);
    dispute_status: (string | null);
    funded_at: (string | null);
    delivered_at: (string | null);
    release_requested_at: (string | null);
    released_at: (string | null);
    auto_release_at: (string | null);
    release_trigger: (string | null);
    created_at: string;
    updated_at: string;
};

export type FeeOut = {
    total: number;
    service_fee: number;
    insurance_fee: number;
    vat: number;
};

export type FeeRequest = {
    to_district_id: number;
    to_ward_code: string;
    weight_grams?: number;
    insurance_value?: number;
};

export type FollowedSellerCollection = {
    items: Array<FollowedSellerItem>;
    total: number;
    skip: number;
    limit: number;
};

export type FollowedSellerItem = {
    created_at: string;
    seller: UserPublic;
};

/**
 * Dữ liệu gửi lên khi quên mật khẩu
 */
export type ForgotPasswordRequest = {
    email: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListingCreate = {
    title: string;
    description?: (string | null);
    price: (number | string);
    is_negotiable?: boolean;
    condition_grade: ConditionGrade;
    category_id: string;
};

/**
 * Response schema for listing images
 */
export type ListingImageRead = {
    id: string;
    listing_id: string;
    image_url: string;
    is_primary: boolean;
    created_at: string;
};

/**
 * Response schema for paginated listings
 */
export type ListingPaginated = {
    items?: Array<ListingWithImages>;
    total: number;
    skip: number;
    limit: number;
};

export type ListingRead = {
    title: string;
    description?: (string | null);
    price: string;
    is_negotiable?: boolean;
    condition_grade: ConditionGrade;
    category_id: string;
    id: string;
    seller_id: string;
    status: ListingStatus;
    rejection_reason?: (string | null);
    view_count?: number;
    save_count?: number;
    is_featured?: boolean;
    published_at?: (string | null);
    location_summary?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Status of a listing.
 */
export type ListingStatus = 'pending' | 'active' | 'sold' | 'hidden' | 'rejected';

/**
 * Status of a listing.
 */
export const ListingStatus = {
    PENDING: 'pending',
    ACTIVE: 'active',
    SOLD: 'sold',
    HIDDEN: 'hidden',
    REJECTED: 'rejected'
} as const;

export type ListingUpdate = {
    title?: (string | null);
    description?: (string | null);
    price?: (number | string | null);
    is_negotiable?: (boolean | null);
    condition_grade?: (ConditionGrade | null);
    category_id?: (string | null);
    status?: (ListingStatus | null);
};

/**
 * Response schema for listing with images
 */
export type ListingWithImages = {
    title: string;
    description?: (string | null);
    price: string;
    is_negotiable?: boolean;
    condition_grade: ConditionGrade;
    category_id: string;
    id: string;
    seller_id: string;
    status: ListingStatus;
    rejection_reason?: (string | null);
    view_count?: number;
    save_count?: number;
    is_featured?: boolean;
    published_at?: (string | null);
    location_summary?: (string | null);
    created_at: string;
    updated_at: string;
    images?: Array<ListingImageRead>;
    seller_name?: (string | null);
    seller_avatar_url?: (string | null);
};

/**
 * Generic response message.
 */
export type MessageResponse = {
    message: string;
};

export type NotificationRead = {
    user_id: string;
    type: NotificationType;
    title: string;
    message: string;
    data?: ({
    [key: string]: unknown;
} | null);
    id: string;
    is_read: boolean;
    created_at: string;
};

/**
 * Phản hồi thông báo có phân trang
 */
export type NotificationsPaginated = {
    items: Array<NotificationRead>;
    total: number;
    page: number;
    page_size: number;
    total_pages: number;
};

/**
 * Type of notification.
 */
export type NotificationType = 'listing_approved' | 'listing_rejected' | 'offer_received' | 'offer_accepted' | 'offer_rejected' | 'offer_countered' | 'offer_expired' | 'order_created' | 'order_confirmed' | 'order_shipping' | 'order_delivered' | 'order_completed' | 'order_cancelled' | 'order_status_updated' | 'review_received' | 'wallet_balance_updated' | 'wallet_locked' | 'wallet_released';

/**
 * Type of notification.
 */
export const NotificationType = {
    LISTING_APPROVED: 'listing_approved',
    LISTING_REJECTED: 'listing_rejected',
    OFFER_RECEIVED: 'offer_received',
    OFFER_ACCEPTED: 'offer_accepted',
    OFFER_REJECTED: 'offer_rejected',
    OFFER_COUNTERED: 'offer_countered',
    OFFER_EXPIRED: 'offer_expired',
    ORDER_CREATED: 'order_created',
    ORDER_CONFIRMED: 'order_confirmed',
    ORDER_SHIPPING: 'order_shipping',
    ORDER_DELIVERED: 'order_delivered',
    ORDER_COMPLETED: 'order_completed',
    ORDER_CANCELLED: 'order_cancelled',
    ORDER_STATUS_UPDATED: 'order_status_updated',
    REVIEW_RECEIVED: 'review_received',
    WALLET_BALANCE_UPDATED: 'wallet_balance_updated',
    WALLET_LOCKED: 'wallet_locked',
    WALLET_RELEASED: 'wallet_released'
} as const;

export type OfferCreate = {
    /**
     * The price offered by the buyer
     */
    offer_price: (number | string);
    /**
     * The listing ID to make an offer on
     */
    listing_id: string;
};

export type OfferRead = {
    /**
     * The price offered by the buyer
     */
    offer_price: string;
    id: string;
    listing_id: string;
    buyer_id: string;
    status: OfferStatus;
    created_at: string;
    updated_at: string;
    order_id?: (string | null);
};

/**
 * Status of an offer (negotiation).
 */
export type OfferStatus = 'pending' | 'accepted' | 'rejected' | 'countered' | 'expired';

/**
 * Status of an offer (negotiation).
 */
export const OfferStatus = {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected',
    COUNTERED: 'countered',
    EXPIRED: 'expired'
} as const;

export type OfferStatusUpdate = {
    /**
     * New status for the offer (ACCEPTED, REJECTED, COUNTERED)
     */
    status: OfferStatus;
    offer_price?: (number | string | null);
};

export type OnboardingStatusResponse = {
    account_id: (string | null);
    onboarding_complete: boolean;
    account_status: (string | null);
    charges_enabled: boolean;
    payouts_enabled: boolean;
};

/**
 * Request body for opening a dispute.
 */
export type OpenDisputeRequest = {
    /**
     * Reason for dispute
     */
    reason: string;
};

export type OrderDirectCreate = {
    listing_id: string;
    payment_method?: PaymentMethod;
    shipping_address?: (ShippingAddressInput | null);
};

export type OrderEventRead = {
    id: string;
    order_id: string;
    event_type: string;
    detail?: (string | null);
    actor_id?: (string | null);
    created_at: string;
};

export type OrderRead = {
    final_price: string;
    id: string;
    buyer_id: string;
    seller_id: string;
    listing_id: string;
    status: OrderStatus;
    payment_method?: PaymentMethod;
    shipping_provider?: (string | null);
    shipping_service_type?: (number | null);
    shipping_fee?: (string | null);
    tracking_number?: (string | null);
    expected_delivery_at?: (string | null);
    delivered_at?: (string | null);
    shipping_name?: (string | null);
    shipping_phone?: (string | null);
    shipping_province?: (string | null);
    shipping_district?: (string | null);
    shipping_ward?: (string | null);
    shipping_address_detail?: (string | null);
    shipping_note?: (string | null);
    shipping_province_id?: (number | null);
    shipping_district_id?: (number | null);
    shipping_ward_code?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Status of an order.
 */
export type OrderStatus = 'pending' | 'confirmed' | 'shipping' | 'delivered' | 'delivery_failed' | 'returning' | 'returned' | 'completed' | 'cancelled';

/**
 * Status of an order.
 */
export const OrderStatus = {
    PENDING: 'pending',
    CONFIRMED: 'confirmed',
    SHIPPING: 'shipping',
    DELIVERED: 'delivered',
    DELIVERY_FAILED: 'delivery_failed',
    RETURNING: 'returning',
    RETURNED: 'returned',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled'
} as const;

export type OrderStatusUpdate = {
    status: OrderStatus;
};

/**
 * Phương thức thanh toán.
 */
export type PaymentMethod = 'wallet' | 'cod';

/**
 * Phương thức thanh toán.
 */
export const PaymentMethod = {
    WALLET: 'wallet',
    COD: 'cod'
} as const;

export type PriceBandRead = {
    label: string;
    min_price: (number | null);
    max_price: (number | null);
    count: number;
};

export type ProvinceOut = {
    province_id: number;
    province_name: string;
};

/**
 * Dữ liệu gửi lên khi Access Token hết hạn
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Dữ liệu gửi lên khi gửi lại email xác minh
 */
export type ResendVerificationRequest = {
    email: string;
};

/**
 * Dữ liệu gửi lên khi đặt lại mật khẩu
 */
export type ResetPasswordRequest = {
    token: string;
    /**
     * Mật khẩu mới: 12+ ký tự, 1 in hoa, 1 thường, 1 số, 1 ký tự đặc biệt
     */
    new_password: string;
};

/**
 * Admin resolution for disputed escrow.
 */
export type ResolveEscrowRequest = {
    /**
     * release: transfer to seller, refund: return funds to buyer
     */
    result: 'release' | 'refund';
    /**
     * Optional admin note
     */
    note?: (string | null);
};

/**
 * release: transfer to seller, refund: return funds to buyer
 */
export type result = 'release' | 'refund';

/**
 * release: transfer to seller, refund: return funds to buyer
 */
export const result = {
    RELEASE: 'release',
    REFUND: 'refund'
} as const;

export type ReturnOrderRequest = {
    order_id: string;
    reason?: (string | null);
};

export type ReturnReason = 'wrong_item' | 'defective' | 'damaged' | 'not_as_described' | 'fake' | 'no_longer_needed';

export const ReturnReason = {
    WRONG_ITEM: 'wrong_item',
    DEFECTIVE: 'defective',
    DAMAGED: 'damaged',
    NOT_AS_DESCRIBED: 'not_as_described',
    FAKE: 'fake',
    NO_LONGER_NEEDED: 'no_longer_needed'
} as const;

export type ReturnRequestCreate = {
    order_id: string;
    reason: ReturnReason;
    description?: (string | null);
    images?: Array<(string)>;
};

export type ReturnRespond = {
    approve: boolean;
    message?: (string | null);
};

export type ReturnShipInput = {
    return_tracking_number: string;
    return_carrier?: (string | null);
};

export type ReviewCreate = {
    order_id: string;
    rating: number;
    comment?: (string | null);
};

export type ReviewRead = {
    order_id: string;
    rating: number;
    comment?: (string | null);
    id: string;
    reviewer_id: string;
    reviewee_id: string;
    created_at: string;
};

export type SavedListingCollection = {
    items: Array<SavedListingItem>;
    total: number;
    skip: number;
    limit: number;
};

export type SavedListingItem = {
    saved_at: string;
    listing: ListingWithImages;
};

export type ServiceOut = {
    service_id: number;
    short_name: string;
    service_type_id: number;
};

export type ShippingAddressInput = {
    name: string;
    phone: string;
    province: string;
    district: string;
    ward: string;
    address_detail: string;
    note?: (string | null);
    province_id?: (number | null);
    district_id?: (number | null);
    ward_code?: (string | null);
};

export type ShippingOrderOut = {
    order_code: string;
    expected_delivery_time: string;
    total_fee: number;
    tracking_url?: string;
};

export type ShippingOrderRequest = {
    order_id: string;
    to_name?: (string | null);
    to_phone?: (string | null);
    to_address?: (string | null);
    to_ward_code?: (string | null);
    to_district_id?: (number | null);
    to_province_id?: (number | null);
    weight_grams?: number;
    insurance_value?: number;
    note?: (string | null);
    service_type_id?: number;
};

export type StaticContentCollection = {
    items: Array<StaticContentRead>;
};

export type StaticContentRead = {
    id: string;
    key: string;
    title: string;
    body: string;
    locale: string;
    version: number;
    created_at: string;
    updated_at: string;
};

/**
 * Dữ liệu Backend trả về khi Đăng nhập thành công
 */
export type TokenResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
    user: UserPrivate;
};

/**
 * Paginated transaction list response.
 */
export type TransactionListResponse = {
    transactions: Array<TransactionRead>;
    total: number;
};

/**
 * Wallet transaction response.
 */
export type TransactionRead = {
    id: string;
    wallet_id: string;
    amount: string;
    type: string;
    description: (string | null);
    order_id: (string | null);
    escrow_id: (string | null);
    payment_gateway_ref?: (string | null);
    bank_code?: (string | null);
    bank_account?: (string | null);
    status?: string;
    balance_before: string;
    balance_after: string;
    created_at: string;
};

/**
 * Current user profile response
 */
export type UserMe = {
    id: string;
    email: string;
    full_name: string;
    phone?: (string | null);
    is_active: boolean;
    is_email_verified: boolean;
    role: string;
    avatar_url?: (string | null);
    rating_avg?: number;
    rating_count?: number;
    trust_score?: number;
    created_at: string;
    updated_at: string;
};

/**
 * Private user profile (full info for authenticated user).
 */
export type UserPrivate = {
    email: string;
    full_name: string;
    phone?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    province?: (string | null);
    district?: (string | null);
    ward?: (string | null);
    address_detail?: (string | null);
    is_phone_verified?: boolean;
    is_email_verified?: boolean;
    shop_name?: (string | null);
    shop_description?: (string | null);
    shop_verified?: boolean;
    /**
     * Estimated response time in minutes
     */
    shop_response_time?: (number | null);
    last_active_at?: (string | null);
    follower_count?: number;
    following_count?: number;
    sales_count?: number;
    trust_score?: string;
    rating_avg?: string;
    rating_count?: number;
    completed_orders?: number;
    role?: UserRole;
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Public user profile (minimal info for other users).
 */
export type UserPublic = {
    id: string;
    full_name: string;
    avatar_url?: (string | null);
    bio?: (string | null);
    trust_score: string;
    rating_avg: string;
    rating_count: number;
    completed_orders: number;
    shop_name?: (string | null);
    shop_description?: (string | null);
    shop_verified?: boolean;
    follower_count?: number;
    sales_count?: number;
    created_at: string;
};

/**
 * Request body for user registration (sign up).
 */
export type UserRegister = {
    email: string;
    full_name: string;
    /**
     * Password must be at least 8 characters
     */
    password: string;
    phone?: (string | null);
};

/**
 * User roles in the system.
 */
export type UserRole = 'user' | 'admin';

/**
 * User roles in the system.
 */
export const UserRole = {
    USER: 'user',
    ADMIN: 'admin'
} as const;

/**
 * Response body for listing users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Update user status
 */
export type UserStatusUpdate = {
    is_active: boolean;
};

/**
 * Request body for updating user profile.
 */
export type UserUpdate = {
    full_name?: (string | null);
    phone?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    province?: (string | null);
    district?: (string | null);
    ward?: (string | null);
    address_detail?: (string | null);
    shop_name?: (string | null);
    shop_description?: (string | null);
    shop_verified?: (boolean | null);
    shop_response_time?: (number | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Dữ liệu gửi lên khi xác minh email
 */
export type VerifyEmailRequest = {
    token: string;
};

/**
 * Wallet information response.
 */
export type WalletRead = {
    id: string;
    user_id: string;
    balance: string;
    locked_balance: string;
    created_at: string;
    updated_at: string;
};

/**
 * Request body for demo topup.
 */
export type WalletTopupRequest = {
    /**
     * Amount to add (max 10,000,000 VND)
     */
    amount: (number | string);
};

export type WardOut = {
    ward_code: string;
    ward_name: string;
};

export type WithdrawRequest = {
    amount: (number | string);
};

export type WithdrawResponse = {
    id: string;
    amount: string;
    status: string;
    message: string;
};

export type GetDashboardStatsApiV1AdminDashboardGetResponse = (unknown);

export type ListUsersApiV1AdminUsersGetData = {
    limit?: number;
    skip?: number;
};

export type ListUsersApiV1AdminUsersGetResponse = (Array<UserMe>);

export type UpdateUserAccountStatusApiV1AdminUsersUserIdStatusPatchData = {
    requestBody: UserStatusUpdate;
    userId: string;
};

export type UpdateUserAccountStatusApiV1AdminUsersUserIdStatusPatchResponse = (UserMe);

export type GetPendingListingsRouteApiV1AdminListingsPendingGetData = {
    limit?: number;
    skip?: number;
};

export type GetPendingListingsRouteApiV1AdminListingsPendingGetResponse = (Array<ListingRead>);

export type ApproveListingApiV1AdminListingsListingIdApprovePostData = {
    listingId: string;
};

export type ApproveListingApiV1AdminListingsListingIdApprovePostResponse = (ListingRead);

export type RejectListingRouteApiV1AdminListingsListingIdRejectPostData = {
    listingId: string;
    requestBody?: Body_reject_listing_route_api_v1_admin_listings__listing_id__reject_post;
};

export type RejectListingRouteApiV1AdminListingsListingIdRejectPostResponse = (ListingRead);

export type ResolveEscrowDisputeApiV1AdminEscrowsOrderIdResolvePostData = {
    orderId: string;
    requestBody: ResolveEscrowRequest;
};

export type ResolveEscrowDisputeApiV1AdminEscrowsOrderIdResolvePostResponse = (unknown);

export type ListAuditTrailApiV1AdminAuditTrailGetData = {
    action?: (string | null);
    limit?: number;
    skip?: number;
    targetType?: (string | null);
};

export type ListAuditTrailApiV1AdminAuditTrailGetResponse = (AdminAuditTrailResponse);

export type RegisterApiV1AuthRegisterPostData = {
    requestBody: UserRegister;
};

export type RegisterApiV1AuthRegisterPostResponse = (TokenResponse);

export type LoginApiV1AuthLoginPostData = {
    formData: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = (TokenResponse);

export type RefreshAccessTokenApiV1AuthRefreshPostData = {
    requestBody: RefreshTokenRequest;
};

export type RefreshAccessTokenApiV1AuthRefreshPostResponse = (TokenResponse);

export type LogoutApiV1AuthLogoutPostResponse = (MessageResponse);

export type VerifyEmailApiV1AuthVerifyEmailPostData = {
    requestBody: VerifyEmailRequest;
};

export type VerifyEmailApiV1AuthVerifyEmailPostResponse = (MessageResponse);

export type ResendVerificationApiV1AuthResendVerificationPostData = {
    requestBody: ResendVerificationRequest;
};

export type ResendVerificationApiV1AuthResendVerificationPostResponse = (MessageResponse);

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
    requestBody: ForgotPasswordRequest;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostResponse = (MessageResponse);

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    requestBody: ResetPasswordRequest;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = (MessageResponse);

export type ListCategoriesApiV1CategoriesGetData = {
    limit?: number;
    skip?: number;
};

export type ListCategoriesApiV1CategoriesGetResponse = (CategoriesPublic);

export type CreateCategoryApiV1CategoriesPostData = {
    args: unknown;
    kwargs: unknown;
    requestBody: CategoryCreate;
};

export type CreateCategoryApiV1CategoriesPostResponse = (CategoryPublic);

export type GetRootCategoriesApiV1CategoriesRootsGetResponse = (Array<CategoryPublic>);

export type GetCategoryBySlugApiV1CategoriesSlugGetData = {
    slug: string;
};

export type GetCategoryBySlugApiV1CategoriesSlugGetResponse = (CategoryPublic);

export type GetCategoryByIdApiV1CategoriesIdCategoryIdGetData = {
    categoryId: string;
};

export type GetCategoryByIdApiV1CategoriesIdCategoryIdGetResponse = (CategoryPublic);

export type UpdateCategoryApiV1CategoriesCategoryIdPutData = {
    args: unknown;
    categoryId: string;
    kwargs: unknown;
    requestBody: CategoryUpdate;
};

export type UpdateCategoryApiV1CategoriesCategoryIdPutResponse = (CategoryPublic);

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteData = {
    args: unknown;
    categoryId: string;
    kwargs: unknown;
};

export type DeleteCategoryApiV1CategoriesCategoryIdDeleteResponse = (void);

export type ListMyConversationsApiV1ChatsConversationsGetData = {
    limit?: number;
    skip?: number;
};

export type ListMyConversationsApiV1ChatsConversationsGetResponse = (Array<ChatConversationRead>);

export type CreateListingConversationApiV1ChatsConversationsListingListingIdPostData = {
    listingId: string;
};

export type CreateListingConversationApiV1ChatsConversationsListingListingIdPostResponse = (ChatConversationRead);

export type GetConversationDetailApiV1ChatsConversationsConversationIdGetData = {
    conversationId: string;
};

export type GetConversationDetailApiV1ChatsConversationsConversationIdGetResponse = (ChatConversationRead);

export type ListMessagesApiV1ChatsConversationsConversationIdMessagesGetData = {
    conversationId: string;
};

export type ListMessagesApiV1ChatsConversationsConversationIdMessagesGetResponse = (Array<ChatMessageRead>);

export type SendMessageApiV1ChatsConversationsConversationIdMessagesPostData = {
    conversationId: string;
    requestBody: ChatMessageCreate;
};

export type SendMessageApiV1ChatsConversationsConversationIdMessagesPostResponse = (ChatMessageRead);

export type GetHelpPagesApiV1ContentHelpGetData = {
    locale?: string;
};

export type GetHelpPagesApiV1ContentHelpGetResponse = (StaticContentCollection);

export type GetLegalPagesApiV1ContentLegalGetData = {
    locale?: string;
};

export type GetLegalPagesApiV1ContentLegalGetResponse = (StaticContentCollection);

export type GetContentApiV1ContentKeyGetData = {
    key: string;
};

export type GetContentApiV1ContentKeyGetResponse = (unknown);

export type RootGetResponse = (unknown);

export type GetEscrowApiV1EscrowsOrderIdGetData = {
    orderId: string;
};

export type GetEscrowApiV1EscrowsOrderIdGetResponse = (EscrowRead);

export type FundEscrowApiV1EscrowsOrderIdFundPostData = {
    orderId: string;
};

export type FundEscrowApiV1EscrowsOrderIdFundPostResponse = (EscrowRead);

export type RequestRefundApiV1EscrowsOrderIdRefundRequestPostData = {
    orderId: string;
    requestBody: OpenDisputeRequest;
};

export type RequestRefundApiV1EscrowsOrderIdRefundRequestPostResponse = (EscrowRead);

export type RequestReleaseApiV1EscrowsOrderIdReleaseRequestPostData = {
    orderId: string;
};

export type RequestReleaseApiV1EscrowsOrderIdReleaseRequestPostResponse = (EscrowRead);

export type ConfirmReleaseApiV1EscrowsOrderIdConfirmReleasePostData = {
    orderId: string;
};

export type ConfirmReleaseApiV1EscrowsOrderIdConfirmReleasePostResponse = (EscrowRead);

export type OpenDisputeApiV1EscrowsOrderIdOpenDisputePostData = {
    orderId: string;
    requestBody: OpenDisputeRequest;
};

export type OpenDisputeApiV1EscrowsOrderIdOpenDisputePostResponse = (EscrowRead);

export type GetDisputedEscrowsApiV1EscrowsDisputedGetData = {
    limit?: number;
    skip?: number;
};

export type GetDisputedEscrowsApiV1EscrowsDisputedGetResponse = ({
    [key: string]: unknown;
});

export type ListListingsApiV1ListingsGetData = {
    categoryId?: (string | null);
    keyword?: (string | null);
    limit?: number;
    maxPrice?: (number | null);
    minPrice?: (number | null);
    sellerId?: (string | null);
    skip?: number;
    sortBy?: 'newest' | 'oldest' | 'price_asc' | 'price_desc' | 'popular' | 'featured';
};

export type ListListingsApiV1ListingsGetResponse = (ListingPaginated);

export type CreateListingApiV1ListingsPostData = {
    requestBody: ListingCreate;
};

export type CreateListingApiV1ListingsPostResponse = (ListingRead);

export type GetFeaturedListingsApiV1ListingsFeaturedGetData = {
    limit?: number;
    skip?: number;
};

export type GetFeaturedListingsApiV1ListingsFeaturedGetResponse = (ListingPaginated);

export type GetTrendingListingsApiV1ListingsTrendingGetData = {
    limit?: number;
    skip?: number;
};

export type GetTrendingListingsApiV1ListingsTrendingGetResponse = (ListingPaginated);

export type GetSearchSuggestionsApiV1ListingsSearchSuggestionsGetData = {
    limit?: number;
    q: string;
};

export type GetSearchSuggestionsApiV1ListingsSearchSuggestionsGetResponse = (Array<(string)>);

export type GetPriceBandSummaryApiV1ListingsPriceBandsGetData = {
    categoryId?: (string | null);
};

export type GetPriceBandSummaryApiV1ListingsPriceBandsGetResponse = (Array<PriceBandRead>);

export type GetMyListingsApiV1ListingsMeGetData = {
    keyword?: (string | null);
    limit?: number;
    skip?: number;
    status?: (ListingStatus | null);
};

export type GetMyListingsApiV1ListingsMeGetResponse = (ListingPaginated);

export type GetRelatedListingsApiV1ListingsListingIdRelatedGetData = {
    limit?: number;
    listingId: string;
    skip?: number;
};

export type GetRelatedListingsApiV1ListingsListingIdRelatedGetResponse = (ListingPaginated);

export type DeleteListingImageRouteApiV1ListingsImagesImageIdDeleteData = {
    imageId: string;
};

export type DeleteListingImageRouteApiV1ListingsImagesImageIdDeleteResponse = (void);

export type GetListingApiV1ListingsListingIdGetData = {
    listingId: string;
};

export type GetListingApiV1ListingsListingIdGetResponse = (ListingWithImages);

export type UpdateListingApiV1ListingsListingIdPatchData = {
    listingId: string;
    requestBody: ListingUpdate;
};

export type UpdateListingApiV1ListingsListingIdPatchResponse = (ListingRead);

export type DeleteListingApiV1ListingsListingIdDeleteData = {
    listingId: string;
};

export type DeleteListingApiV1ListingsListingIdDeleteResponse = (void);

export type UploadListingImageApiV1ListingsListingIdImagesPostData = {
    formData: Body_upload_listing_image_api_v1_listings__listing_id__images_post;
    isPrimary?: boolean;
    listingId: string;
};

export type UploadListingImageApiV1ListingsListingIdImagesPostResponse = (ListingImageRead);

export type GetMyNotificationsApiV1NotificationsGetData = {
    limit?: number;
    skip?: number;
};

export type GetMyNotificationsApiV1NotificationsGetResponse = (NotificationsPaginated);

export type GetUnreadNotificationsCountApiV1NotificationsUnreadCountGetResponse = (unknown);

export type MarkNotificationAsReadApiV1NotificationsNotificationIdReadPutData = {
    notificationId: string;
};

export type MarkNotificationAsReadApiV1NotificationsNotificationIdReadPutResponse = (NotificationRead);

export type MarkAllNotificationsAsReadApiV1NotificationsReadAllPutResponse = (unknown);

export type CreateOfferApiV1OffersPostData = {
    requestBody: OfferCreate;
};

export type CreateOfferApiV1OffersPostResponse = (OfferRead);

export type GetMySentOffersApiV1OffersMeSentGetData = {
    limit?: number;
    skip?: number;
};

export type GetMySentOffersApiV1OffersMeSentGetResponse = (Array<OfferRead>);

export type GetMyReceivedOffersApiV1OffersMeReceivedGetData = {
    limit?: number;
    skip?: number;
};

export type GetMyReceivedOffersApiV1OffersMeReceivedGetResponse = (Array<OfferRead>);

export type GetOffersForListingApiV1OffersListingListingIdGetData = {
    limit?: number;
    listingId: string;
    skip?: number;
};

export type GetOffersForListingApiV1OffersListingListingIdGetResponse = (Array<OfferRead>);

export type UpdateOfferStatusApiV1OffersOfferIdStatusPatchData = {
    offerId: string;
    requestBody: OfferStatusUpdate;
};

export type UpdateOfferStatusApiV1OffersOfferIdStatusPatchResponse = (OfferRead);

export type GetOfferApiV1OffersOfferIdGetData = {
    offerId: string;
};

export type GetOfferApiV1OffersOfferIdGetResponse = (OfferRead);

export type GetMyOrdersApiV1OrdersGetResponse = (Array<OrderRead>);

export type CreateDirectOrderApiV1OrdersPostData = {
    requestBody: OrderDirectCreate;
};

export type CreateDirectOrderApiV1OrdersPostResponse = (OrderRead);

export type GetMyOrdersApiV1OrdersMeGetResponse = (Array<OrderRead>);

export type GetOrderApiV1OrdersOrderIdGetData = {
    orderId: string;
};

export type GetOrderApiV1OrdersOrderIdGetResponse = (OrderRead);

export type GetOrderTimelineApiV1OrdersOrderIdTimelineGetData = {
    orderId: string;
};

export type GetOrderTimelineApiV1OrdersOrderIdTimelineGetResponse = (Array<OrderEventRead>);

export type CompleteOrderApiV1OrdersOrderIdCompletePostData = {
    orderId: string;
};

export type CompleteOrderApiV1OrdersOrderIdCompletePostResponse = (OrderRead);

export type CancelOrderApiV1OrdersOrderIdCancelPostData = {
    orderId: string;
};

export type CancelOrderApiV1OrdersOrderIdCancelPostResponse = (OrderRead);

export type UpdateOrderStatusApiV1OrdersOrderIdStatusPatchData = {
    orderId: string;
    requestBody: OrderStatusUpdate;
};

export type UpdateOrderStatusApiV1OrdersOrderIdStatusPatchResponse = (OrderRead);

export type CreateDepositApiV1PaymentCreateDepositPostData = {
    requestBody: DepositRequest;
};

export type CreateDepositApiV1PaymentCreateDepositPostResponse = (DepositResponse);

export type StripeWebhookApiV1PaymentWebhookPostResponse = (unknown);

export type CreateReturnRequestApiV1ReturnsRequestPostData = {
    requestBody: ReturnRequestCreate;
};

export type CreateReturnRequestApiV1ReturnsRequestPostResponse = (unknown);

export type RespondReturnApiV1ReturnsReturnIdRespondPostData = {
    requestBody: ReturnRespond;
    returnId: string;
};

export type RespondReturnApiV1ReturnsReturnIdRespondPostResponse = (unknown);

export type ShipReturnApiV1ReturnsReturnIdShipPostData = {
    requestBody: ReturnShipInput;
    returnId: string;
};

export type ShipReturnApiV1ReturnsReturnIdShipPostResponse = (unknown);

export type ConfirmReturnReceivedApiV1ReturnsReturnIdConfirmReceivedPostData = {
    returnId: string;
};

export type ConfirmReturnReceivedApiV1ReturnsReturnIdConfirmReceivedPostResponse = (unknown);

export type GetMyReturnRequestsApiV1ReturnsMyRequestsGetData = {
    limit?: number;
    skip?: number;
};

export type GetMyReturnRequestsApiV1ReturnsMyRequestsGetResponse = (unknown);

export type GetSellerReturnRequestsApiV1ReturnsMySellerRequestsGetData = {
    limit?: number;
    skip?: number;
};

export type GetSellerReturnRequestsApiV1ReturnsMySellerRequestsGetResponse = (unknown);

export type CreateReviewApiV1ReviewsPostData = {
    requestBody: ReviewCreate;
};

export type CreateReviewApiV1ReviewsPostResponse = (ReviewRead);

export type GetUserReviewsApiV1ReviewsUserUserIdGetData = {
    userId: string;
};

export type GetUserReviewsApiV1ReviewsUserUserIdGetResponse = (Array<ReviewRead>);

export type GetReviewApiV1ReviewsOrderIdGetData = {
    orderId: string;
};

export type GetReviewApiV1ReviewsOrderIdGetResponse = (Array<ReviewRead>);

export type ListProvincesApiV1ShippingProvincesGetResponse = (Array<ProvinceOut>);

export type ListDistrictsApiV1ShippingDistrictsGetData = {
    provinceId: number;
};

export type ListDistrictsApiV1ShippingDistrictsGetResponse = (Array<DistrictOut>);

export type ListWardsApiV1ShippingWardsGetData = {
    districtId: number;
};

export type ListWardsApiV1ShippingWardsGetResponse = (Array<WardOut>);

export type ListServicesApiV1ShippingServicesGetData = {
    toDistrictId: number;
};

export type ListServicesApiV1ShippingServicesGetResponse = (Array<ServiceOut>);

export type CalculateShippingFeeApiV1ShippingFeePostData = {
    requestBody: FeeRequest;
};

export type CalculateShippingFeeApiV1ShippingFeePostResponse = (FeeOut);

export type CheckAvailabilityApiV1ShippingAvailabilityPostData = {
    toDistrictId: number;
    toWardCode: string;
};

export type CheckAvailabilityApiV1ShippingAvailabilityPostResponse = (AvailabilityOut);

export type CreateShippingOrderApiV1ShippingCreateOrderPostData = {
    requestBody: ShippingOrderRequest;
};

export type CreateShippingOrderApiV1ShippingCreateOrderPostResponse = (ShippingOrderOut);

export type ShippingWebhookApiV1ShippingWebhookPostResponse = (unknown);

export type ReturnShippingOrderApiV1ShippingReturnOrderPostData = {
    requestBody: ReturnOrderRequest;
};

export type ReturnShippingOrderApiV1ShippingReturnOrderPostResponse = (unknown);

export type DeliveryAgainShippingApiV1ShippingDeliveryAgainPostData = {
    requestBody: DeliveryAgainRequest;
};

export type DeliveryAgainShippingApiV1ShippingDeliveryAgainPostResponse = (unknown);

export type ListSavedListingsApiV1SavedListingsGetData = {
    limit?: number;
    skip?: number;
};

export type ListSavedListingsApiV1SavedListingsGetResponse = (SavedListingCollection);

export type SaveListingApiV1SavedListingsListingIdPostData = {
    listingId: string;
};

export type SaveListingApiV1SavedListingsListingIdPostResponse = (SavedListingItem);

export type UnsaveListingApiV1SavedListingsListingIdDeleteData = {
    listingId: string;
};

export type UnsaveListingApiV1SavedListingsListingIdDeleteResponse = (void);

export type ListFollowedSellersApiV1FollowedSellersGetData = {
    limit?: number;
    skip?: number;
};

export type ListFollowedSellersApiV1FollowedSellersGetResponse = (FollowedSellerCollection);

export type FollowSellerApiV1FollowedSellersSellerIdPostData = {
    sellerId: string;
};

export type FollowSellerApiV1FollowedSellersSellerIdPostResponse = (FollowedSellerItem);

export type UnfollowSellerApiV1FollowedSellersSellerIdDeleteData = {
    sellerId: string;
};

export type UnfollowSellerApiV1FollowedSellersSellerIdDeleteResponse = (void);

export type StartOnboardingApiV1ConnectOnboardingPostResponse = (CreateAccountResponse);

export type GetOnboardingStatusApiV1ConnectOnboardingStatusGetResponse = (OnboardingStatusResponse);

export type GetCurrentUserInfoApiV1UsersMeGetResponse = (UserPrivate);

export type UpdateMyProfileApiV1UsersMePutData = {
    requestBody: UserUpdate;
};

export type UpdateMyProfileApiV1UsersMePutResponse = (UserPrivate);

export type ChangePasswordApiV1UsersMePasswordPutData = {
    requestBody: ChangePasswordRequest;
};

export type ChangePasswordApiV1UsersMePasswordPutResponse = (MessageResponse);

export type GetUserProfileApiV1UsersUserIdGetData = {
    userId: string;
};

export type GetUserProfileApiV1UsersUserIdGetResponse = (UserPublic);

export type ListUsersApiV1UsersGetData = {
    limit?: number;
    skip?: number;
};

export type ListUsersApiV1UsersGetResponse = (UsersPublic);

export type HealthCheckApiV1UtilsHealthCheckGetResponse = (unknown);

export type GetMyWalletApiV1WalletMeGetResponse = (WalletRead);

export type DemoTopupApiV1WalletDemoTopupPostData = {
    requestBody: WalletTopupRequest;
};

export type DemoTopupApiV1WalletDemoTopupPostResponse = (WalletRead);

export type WithdrawApiV1WalletWithdrawPostData = {
    requestBody: WithdrawRequest;
};

export type WithdrawApiV1WalletWithdrawPostResponse = (WithdrawResponse);

export type GetTransactionsApiV1WalletTransactionsGetData = {
    limit?: number;
    skip?: number;
};

export type GetTransactionsApiV1WalletTransactionsGetResponse = (TransactionListResponse);